### ISSUE TITLE
Cannot copy concept data from clause/contract into the response

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero#108]
If logic copies data from the contract/clause into the response it will fail validation, because the clause data is not a Composer object:

https://github.com/accordproject/cicero/blob/master/packages/cicero-core/lib/templateinstance.js#L64

**Comment by jeromesimeon** [comment]
It obviously has to revalidate? Another instance of that is when you want to create a new Composer object from scratch to place in the response (or in the state for that matter).

**Comment by jeromesimeon** [comment]
Orthogonal aspect: is that right that composer does not allow to validate concepts? When I tried, I couldn't figure out how to change that line you point to.

**Comment by dselman** [comment]
At line 
https://github.com/accordproject/cicero-template-library/blob/51bb5a66cca37596f57ac7439f075737c6cb2886/installment-sale/lib/logic.js#L67 a cleaner way to do this would be to use the Composer `Factory` to create a new instance.

**Comment by dselman** [comment]
Yes, the clause data is not currently a Composer object - I’m working on that as well.

**Comment by jeromesimeon** [comment]
I think you bumped into that same issue, I just missed some of the initial discussion that led here.

**Comment by dselman** [comment]
Fixed.
