### ISSUE TITLE
Add getEventTypes to template API

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/cicero#116]
Just as with getRequestTypes and getResponseTypes https://github.com/accordproject/cicero/blob/37f5d331d1c03a70558d2f8b34dfcf82d60dd33d/packages/cicero-core/lib/template.js#L1073, the Cicero template JS API should have a function which returns a list of the event types emitted by a clause. 

@jeromesimeon does this imply that we also need an annotation in the compiled JS code to identify the event types?

**Comment by jeromesimeon** [comment]
There is now a corresponding `getEventTypes()` call.
