### ISSUE TITLE
Convert the Ergo Playground to Accord Project Template Studio

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero#141]
The current Ergo Playground is somewhat of a misnomer:
https://github.com/accordproject/ergo-playground/blob/master/dist/bundle.js

It would be clearer if this became Accord Project Template Studio:
- Load a template from https://templates.accordproject.org (other locations nice to have)
- Generate a sample request transaction. Syntax highlighting of the JSON. Form generation nice to have based on https://github.com/uchibeke/composer-form
- Generate sample state
- Submit a transaction to a contract/clause
- Display the new state, response and emitted events
- Edit the Ergo logic
- Save/export the modified template to disk. Save to local storage as well?

**Comment by jeromesimeon** [comment]
link to the playground is here: https://accordproject.github.io/ergo-playground/

**Comment by jeromesimeon** [comment]
Initial design and prototype for a template studio can be found here: https://github.com/accordproject/template-studio

Feature coverage:
It would be clearer if this became Accord Project Template Studio:
- [ ] Load a template from https://templates.accordproject.org (other locations nice to have)
- [x] Generate a sample request transaction.
- [x] Syntax highlighting of the JSON.
- [ ] Form generation nice to have based on https://github.com/uchibeke/composer-form
- [x] Generate sample state
- [x] Submit a transaction to a contract/clause
- [x] Display the new state, response and emitted events
- [x] Edit the Ergo logic
- [ ] Save/export the modified template to disk. Save to local storage as well?

**Comment by jeromesimeon** [comment]
Can we consider this issue resolved, based on https://github.com/accordproject/template-studio and open any additional issues on template studio instead?
