### ISSUE TITLE
Add support for contracts

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero#15]
A contract is composed of a set of clauses. 

- [x] Need some sort of data flow between the clauses
- [ ] Need a function signature for the contract
- [x] Need a composition model for clauses and contracts, so they may be nested or reference each other
- [x] Contract templates should stipulate required/optional clauses (implies clauses need a type)

### Contract Template

- [x] Name
- [x] Version
- [x] Description
- [x] Set of required clause templates
- [x] Set of optional clause templates

### Contract

- [x] Name
- [x] Version
- [x] Description
- [x] Set of clauses
- [x] Link to contract template

**Comment by jeromesimeon** [comment]
A contract may:
- contain definitions
- be tied to a model (actors, entities)
- be validated for consistency (certain clauses must exist, verify some constraints)
- have a state (e.g., Pre-formation, Execution, Breach, Terminated, Renegotiation)

Clauses may:
- Have different functional use wrt. contract (e.g., precondition, normal execution of the contract, default clauses) -- This may relate to the notion of clause type

**Comment by uwecerron** [comment]
Should contracts be explicitly classified on the basis of consideration? i.e: unilateral, bilateral,  multilateral.

**Comment by jeromesimeon** [comment]
@uwecerron Adding a classification sounds like a good idea. Would that replace/complement the `list of parties`, what additional information would be needed?

**Comment by mttrbrts** [comment]
Addressed in https://github.com/accordproject/cicero/projects/1

**Comment by mttrbrts** [comment]
I think that we're all done here except for the Contract signature. Is this something that is still necessary given the new dispatch logic @dselman / @jeromesimeon ?

**Comment by jeromesimeon** [comment]
@mttrbrts I think this should be closed. We can open more specific issues for the remaining parts if any?

**Comment by dselman** [comment]
Agreed
