### ISSUE TITLE
cicero parse failed on Ubuntu

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero#150]
User was using the attached template:
[mytemplate.zip](https://github.com/accordproject/cicero/files/2145489/mytemplate.zip)

**Comment by BombardaIllegale** [comment]
This happened on
Distributor ID:    Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:    16.04
Codename:    xenial

**Comment by jeromesimeon** [comment]
Using  `mytemplate.zip` with two minor fixes: 1. upgrade to Cicero 0.9.9, 2. Fix the sample to remove the `"Test"` part, I  see:

```
bash-3.2$ cicero --version
0.9.9
bash-3.2$ cicero parse 
11:45:31 - info: Using current directory as template folder
11:45:31 - info: Loading a default sample.txt file.
11:45:32 - error: invalid syntax at line 1 col 36:

  Name of the person to greet: "Dan".
                                     ^
Unexpected "\r"

11:45:32 - info: undefined
```

which makes me think it's another duplicate of #197 

@Hippobla can you confirm that it was your issue?

**Comment by jeromesimeon** [comment]
Revised template for reference:
[mytemplate2.zip](https://github.com/accordproject/cicero/files/2654021/mytemplate2.zip)

**Comment by Hippobla** [comment]
I think is the same yes

Il giorno Gio 6 Dic 2018, 18:48 Jerome Simeon <notifications@github.com> ha
scritto:

**Comment by jeromesimeon** [comment]
Thanks! I'll be looking into it. Closing this specific issue as a duplicate.
