### ISSUE TITLE
Contract string variable can't be successfully converted to Date object in logic.js

### ISSUE THREAD

**Issue by MHeisoku** [accordproject/cicero#155]
I have dates in a contract in the form "dd MMM YYYY" (e.g. 01 July 2018) and would like to read these in as Strings and then convert them to Dates in logic.js. Using var d = new Date(contractVar); returns an "Invalid Date". I have confirmed that the date string is coming into logic.js from the contract parsing correctly. Also I have tested string to date conversion using the same method by feeding the same date as a static string in logic.js and it works as expected.

What could be causing this and is there a workaround to this issue for the moment?

Cicero CLI version 0.4.5.

**Comment by jeromesimeon** [comment]
hi @MHeisoku Would you be able to post a simple corresponding code which illustrate this problem? (e.g., a small grammar, sample, CTO and logic).

In most templates we avoid the use of `Date` directly and uses the moment library from https://momentjs.com

You can parse dates using e.g., `moment("1995-12-25");`. And according to the moment library documentation date has to be in ISO 8601 format. https://momentjs.com/docs/#/parsing/string/

**Comment by MHeisoku** [comment]
Thanks Jerome. That helped to debug the issue - turns out you can parse dates in the form "01 January 2018" pretty easily with moment so long as you provide a string format. I ended up using var d = moment(dateString, "DD MMMM YYYY") and it worked.
