### ISSUE TITLE
Concrete template instantiation

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/cicero#161]
Currently, a clause instance is instantiated in JS with the following code:

	const clause = new Clause(template);

Should templates be JS modules so that I could write:

	const clause = new PaymentClause(amount);

Where the clause constructor is parameterised by the template model 

For contract instantiation, we must also consider initialization logic for the contract. The `init` clause:
- sets the default contract state 
- can emit immediate obligations (ref. one-time-payment, https://github.com/accordproject/cicero-template-library/blob/master/src/one-time-payment/lib/logic.ergo)
- Potentially puts conditions on the values of the template model ❓ 

This is related to https://github.com/accordproject/cicero/issues/160

The Ergo compiler already generates JS classes which could be used to support this.

**Comment by dselman** [comment]
What problem is this solving?

**Comment by mttrbrts** [comment]
This is still half-baked, more thinking required.

Superficially, my motivation was to reduce the operations required to instantiate a Clause. 

However there is a risk that we lose some elements of the template. I.e. perhaps just using the compiled Ergo logic.

**Comment by jeromesimeon** [comment]
Does it make sense to instantiate a clause instance. Should we instantiate contracts instead?

**Comment by Cronus1007** [comment]
@mttrbrts How the elements are going to be lost with such an initialization?All the elements can be transferred in a safe manner I guess.

**Comment by mttrbrts** [comment]
This is a stale idea. Closing
