### ISSUE TITLE
Support for private template libraries

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/cicero#164]
The templateLibrary class in cicero-core should support auth-headers to allow connection to private protected libraries too.

https://github.com/accordproject/cicero/blob/master/packages/cicero-core/lib/templatelibrary.js

**Comment by triebben** [comment]
Hi, will take this issue if nobody else already working on it.

I think the library is now located at https://github.com/accordproject/cicero/blob/master/packages/cicero-core/src/templatelibrary.js

**Comment by irmerk** [comment]
> Hi, will take this issue if nobody else already working on it.
> 
> I think the library is now located at https://github.com/accordproject/cicero/blob/master/packages/cicero-core/src/templatelibrary.js

@mttrbrts or @jeromesimeon you would likely know the answer to this.

**Comment by mttrbrts** [comment]
Thanks @triebben, you're welcome to take this. No-one has made progress on this that I'm aware of.

Do you have a proposal for authentication schemes? Making this extensible is important, IMO.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization

HTTP Basic Auth seems like the obvious first step, but I can imagine in the future a need to support Bearer, AWS4, OAuth etc.

Maybe @roysjosh has some thoughts?

**Comment by jeromesimeon** [comment]
> Hi, will take this issue if nobody else already working on it.
> 
> I think the library is now located at https://github.com/accordproject/cicero/blob/master/packages/cicero-core/src/templatelibrary.js

@triebben This is correct the `./lib` directory is not generated from `./src`

**Comment by triebben** [comment]
Hi, at first place [TemplateLibrary constructor](https://github.com/accordproject/cicero/blob/master/packages/cicero-core/src/templatelibrary.js#L44) should be extended to receive credentials.

Maybe parameter like username and password
```javascript
class TemplateLibrary {
    constructor(url=null, user=null, password=null) {
       ...
```
or a advanced version to set an authentication object for different HTTP Auth 
```javascript
class TemplateLibrary {
    constructor(url=null, auth=null) {
       ...

let auth = {
   type: "Basic",
   credential: "YWxhZGRpbjpvcGVuc2VzYW1l"
}
```
for example.

These attributes can be pasted to [request lib](https://github.com/accordproject/cicero/blob/master/packages/cicero-core/src/templatelibrary.js#L132) to use as authentication against a template library.

**Comment by mttrbrts** [comment]
I prefer the second option (even if we only support Basic auth to begin), it means that we don't have to make a breaking API change when we want to add other auth types.

**Comment by triebben** [comment]
PullRequest is open.

I can't find any function to mock a request inside current cicero-core testing. So i'm not able to verify if a request actually contains the provided http authentication header.
Is there a way to mock/ intercept request with current test setting?

**Comment by irmerk** [comment]
Anyone working on this, please see discussion and code in #426

**Comment by Cronus1007** [comment]
@irmerk @mttrbrts Shall I work upon this issue.

**Comment by irmerk** [comment]
Sure thing @Cronus1007, I think we should agree on a plan as this one should be challenging.

**Comment by Cronus1007** [comment]
@irmerk The plan that I intend to follow is :-
- [ ] While looking upto #426 I will make the required changes that were present in it.
- [ ] Then make these changes as told by @mttrbrts in https://github.com/accordproject/cicero/pull/426#issuecomment-543614375

**Comment by mttrbrts** [comment]
> @irmerk The plan that I intend to follow is :-
> - [ ] While looking upto #426 I will make the required changes that were present in it.
> - [ ] Then make these changes as told by @mttrbrts in https://github.com/accordproject/cicero/pull/426#issuecomment-543614375
> 
> Does it sound a good plan? If there are few additions or deletion to it let me know.
> 

Yes, those linked comments summarise the problem well. Let us know if you have further questions

**Comment by Cronus1007** [comment]
@mttrbrts In `getTemplate` function shall I create the condition if the user is not authenticated then user gets returned with the cache else gets the template.Whats your opinion?

And addressing your questions in the pr #426 different credentials for the same library doesn't make much sense.Since if the user requires different credentials for same library then there is not point of authentication i guess.

**Comment by mttrbrts** [comment]
Perhaps instead the credentials / auth header should be a property to the `TemplateLibrary` constructor. That way any method that needs them (e.g. `getTemplate`, `getTemplateIndex`) has them in scope. This also means that we don't need to change the API of multiple functions.

**Comment by Cronus1007** [comment]
@mttrbrts Have a look upon the PR #623 and tell the required changes.

> Perhaps instead the credentials / auth header should be a property to the `TemplateLibrary` constructor. That way any method that needs them (e.g. `getTemplate`, `getTemplateIndex`) has them in scope. This also means that we don't need to change the API of multiple functions.

**Comment by Cronus1007** [comment]
@mttrbrts In `getTemplate` and `getTemplateIndex` for just the sake of checking of `httpHeader` variable added few `logger` statements.
