### ISSUE TITLE
Concrete syntax for Contract Template DOM

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero#171]
The structure of a full contract and clause template is determined by the Cicero DOM:
https://models.accordproject.org/cicero/dom.html

Also see #79 

We need to decide on a concrete syntax for the DOM that we want to put in the Cicero Template Archive.

The proposed name for this syntax is: `TBD`.

The assumption is that non-technical users will use an editor (web or embedded in MS Word) to edit Cicero contracts (rather than editing this syntax directly), however it is valuable for technical users to have a concrete syntax that is amenable to editing in Emacs, VS Code etc and that integrates smoothly with Git-based workflows for change management.

Current proposals are:
- Just use the native JSON serialization
- An XML Schema defined serialization
- A Nunjucks inspired serialization
- A Markdown inspired serialization
- Subset of HTML

References:
- Common Form: https://commonform.org/kemitchell/apache-2/1e
- Common Accord: http://www.commonaccord.org/index.php?action=source&file=G/US-Constitution-CmA/Article/1.md
- OpenLaw: https://docs.openlaw.io/markdown/index.html
- Legal Document ML: http://docs.oasis-open.org/legaldocml/akn-core/v1.0/akn-core-v1.0-part1-vocabulary.html
- https://tools.ietf.org/html/rfc1896
- http://doc.qt.io/archives/qt-4.8/richtext-html-subset.html
- Commonmark: https://github.com/commonmark/commonmark.js

Native JSON:
```
{
    "$class" : "org.accordproject.cicero.dom.ContractTemplate",
    "id" : "contract-001",
    "content" : {
        "$class" : "org.accordproject.cicero.dom.Section",
        "id" : "section-001",
        "heading" : {
            "$class" : "org.accordproject.cicero.dom.Text",
            "content" : "LAND SALE CONTRACT",
            "id" : "section-001-heading"
        },
        "children" : [
            {
                "$class" : "org.accordproject.cicero.dom.Text",
                "id" : "sections-001-001",
                "content" : "The first party (henceforth known as "Buyer") agrees to purchase from the second party (henceforth known as "Seller") the land (henceforth known as "Land") located at the following address:",
            },
            {
                "$class" : "org.accordproject.cicero.dom.Parameter",
                "id" : "parameter-address",
                "name" : "address"
            },
            {
                "$class" : "org.accordproject.cicero.dom.Text",
                "id" : "sections-001-003",
                "content" : ", in the city of "
            },
            {
                "$class" : "org.accordproject.cicero.dom.Parameter",
                "id" : "parameter-city",
                "name" : "city"
            }
        ]
    }
}
```

XML:

```
<!DOCTYPE accordproject>

<contract>
  <ergo>
    define function area(r : float) : float { return pi * r^2.0 }
  </ergo>

  <section name="land-sale-contract">
    <h1>Land Sale Contract</h1>
    <p>The first party (henceforth known as the <defn>Buyer</defn>) agrees to
    purchase from the second party (henceforth known as <defn>Seller</defn>)
    the land (henceforth known as the <defn>Land</defn>) located at the
    following address:
    <input name="address" class="org.accordproject.address"/>,
    in the city of
    <input name="city" class="org.accordproject.string"/>.

    <!-- we can reference past definitions inline pretty easily -->
    The <term>Buyer</term> shall pay the <term>Seller</term> for the land.

    <!-- tables come for free -->
    <table>
      <tr>...</tr>
    </table>

    <!-- comments come for free, too, now that I think about it -->

    <!-- ordered/unordered lists come for free -->
    These countries are exempt from this contract:
    <ul>
      <li>Canada
      <li>Mexico
    </ul>

    <!-- and of course basic formatting -->
    <strong>Note:</strong> This contract does <em>not</em> apply to so-and-so.

    <signature>
      <name>Dan Selman</name>
      <affiliation>Clause, Inc.</affiliation>
      <date>July 26, 2018</date>
    </signature>

    <signature>
      <name>Kartik Chandra</name>
      <affiliation>Stanford University</affiliation>
      <date>July 26, 2018</date>
    </signature>
  </section>
</contract>
```

**Comment by kach** [comment]
(I like the XML syntax… 😄)

**Comment by jeromesimeon** [comment]
I'll add a markup version for comparison, inspired by nunjucks:
```
{% contract %}
  {{
    define function area(r : float) : float { return pi * r^2.0 }
  }}

  {% section:land-sale-contract %}
  {% title %}Land Sale Contract{% endtitle %}

  The first party (henceforth known as the {[Buyer]}) agrees to
  purchase from the second party (henceforth known as {[Seller]}) the
  land (henceforth known as the {[Land]}) located at the following
  address:
    
    {[address:org.accordproject.address]}, in the city of
    {[city:org.accordproject.string]}.

    {# we can reference past definitions inline pretty easily #}
    The {{ contract.address }} shall pay the {{ contract.city }} for the land.

    {# tables do not come for free #}
    {% table %}
      {% row %}...{% endrow %}
    {% endtable %}

    {# comments come for free, though, now that I think about it #}

    {% lists do not come for free %}
    These countries are exempt from this contract:
    {% list %}
      {% item %}Canada{% item %}
      {% item %}Mexico{% item %}
    {% list %}

    {# and of course no formatting #}
    Note: This contract does not apply to so-and-so.

    {% signature %}
      {{ contract.Buyer }}
      {[ buyerAffiliation ]}
      {[ buyerSignedDate ]}
    { %signature %}

    {% signature %}
      {{ contract.Seller }}
      {[ sellerAffiliation ]}
      {[ sellerSignedDate ]}
    {% signature %}

  {% endsection %}
{% endcontract %}
```

**Comment by mttrbrts** [comment]
I had something more like this in mind...

While Markdown is much less expressive and extensible than XML, this option has the advantage of legibility by a less technical user. The trade-off is that extensions need to be written in HTML, and introduce two notations to the concrete syntax.

```
<code>
    define function area(r : float) : float { return pi * r^2.0 }
<code>

# Land Sale Contract

The first party (henceforth known as the {[Buyer]}) agrees to
purchase from the second party (henceforth known as {[Seller]}) the
land (henceforth known as the {[Land]}) located at the following
address:
    
{[address:org.accordproject.address]}, in the city of
{[city]}. <!-- This has an implicit String type -->

<!-- we can reference past definitions inline pretty easily -->
The {{ contract.address }} shall pay the {{ contract.city }} for the land.

<!-- tables come for free -->
| Header 1 | Header 2 |
| --------- |--------- |
| Row 1       |  Cell 2 .   |

<!-- comments come for free, though, now that I think about it -->

These countries are exempt from this contract:
- Canada
- Mexico

<!-- and of course basic formatting -->
**Note:** This contract does *not* apply to so-and-so.

<!-- extensions can be written in HTML style --> 
<div class="signature">
    {{ contract.Buyer }}
    *{[ buyerAffiliation ]}*
    {[ buyerSignedDate ]}
</div>

<div class="signature">
    {{ contract.Seller }}
    *{[ sellerAffiliation ]}*
    {[ sellerSignedDate ]}
</div>

<!-- extensions can be written in HTML style --> 
<div style="page-break-after: always" />
```

And by way of demonstrating one advantage, here's the rendering of the same template in GitHub.

<blockquote>
  <code>
    define function area(r : float) : float { return pi * r^2.0 }
  </code>

  # Land Sale Contract

  The first party (henceforth known as the {[Buyer]}) agrees to
  purchase from the second party (henceforth known as {[Seller]}) the
  land (henceforth known as the {[Land]}) located at the following
  address:
    
  {[address:org.accordproject.address]}, in the city of
  {[city]}. 

  
  The {{ contract.address }} shall pay the {{ contract.city }} for the land.

  
  | Header 1 | Header 2 |
  | --------- |--------- |
  | Row 1       |  Cell 2 .   |

  

  These countries are exempt from this contract:
  - Canada
  - Mexico

  
  **Note:** This contract does *not* apply to so-and-so.

   
  <div class="signature">
  {{ contract.Buyer }}
  *{[ buyerAffiliation ]}*
  {[ buyerSignedDate ]}
  </div>

  <div class="signature">
  {{ contract.Seller }}
  *{[ sellerAffiliation ]}*
  {[ sellerSignedDate ]}
  </div>

   
  <div style="page-break-after: always" />
</blockquote>

**Comment by mttrbrts** [comment]
Note that none of these examples capture the logical parts of the DOM, e.g. choice or conditional sections. And the XML and MD examples don't include unbounded lists.

## For JSON
```json
{
        "$class" : "org.accordproject.cicero.dom.Choice",
        "required": true,
        "elements": [ 
             {
                  "$class" : "org.accordproject.cicero.dom. Conditional",
                  "element": { ... },
                  "predicate": "enforce value % 10 = 0"
              },
              { ... }
        ]
}

```

## For XML
```xml
<choice required="true">
  <choiceOption>
    <conditionalSection predicate="enforce value % 10 = 0">
      ..
    </conditonalSection>
  </choiceOption>
  <choiceOption>
     ....
  </choiceOption>
</choice>
```

## For Jinja2 / Nunjucks style
```
{# blocks delimit the choices here #}
{% choice %}
  {% if value % 10 = 0 %}
    ...
  {% endif %}
  ...
{% endchoice %}

```

## For Markdown style
We could choose something like the Jijna2 / Nunjucks option above, or otherwise something like Mustache / Handbars.
```
{{#choice}}
  {{#if value % 10 = 0}}
    ..
  {{/if}}
{{/choice}}
```

**Comment by dselman** [comment]
@mttrbrts what is the quality of the output from the Markdown parser, particularly for the inline HTML?

**Comment by dselman** [comment]
@jeromesimeon what is the quality of the output from the Nunjucks parser? Would we have to roll our own parser?

**Comment by mttrbrts** [comment]
Default Remark AST from the sample above, https://gist.github.com/mttrbrts/257bc23c22707201075e75e70052a10b
We'd need to add a plug-in to support the variables etc.

**Comment by dselman** [comment]
In terms of openness of the implementation (ability to parse the DOM on a wide variety of platforms), I think the XML syntax has the edge. Are there other factors people think should be considered, other than:

- Openness
- Extensibility
- Readability
- Learning Curve

**Comment by kach** [comment]
* Amount of existing tooling we can leverage (not just parsers and serializers, but also smaller things like editor plug-ins, etc.)

**Comment by dselman** [comment]
Some work in progress based on the generated XSD (which a minor tweak to remove the ns prefix for `org.accordproject.cicero.dom`): https://models.accordproject.org/cicero/dom.html

It's not particularly pretty, but it's powerful and easy to parse in any language. We can make it a bit more palatable by using attributes for some stuff and making more of it optional (encoding for example).

Interested in people's thoughts.

```
<?xml version="1.0" encoding="UTF-8"?>
<ContractTemplate
	xmlns:org.accordproject.cicero.contract="org.accordproject.cicero.contract"
	xmlns="org.accordproject.cicero.dom"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="org.accordproject.cicero.dom org.accordproject.cicero.dom.xsd ">
	<id>id</id>
	<metadata>
		<version>1.0</version>
		<locale>en-US</locale>
	</metadata>
	<content xsi:type="Section">
		<id>SECTION_001</id>
		<heading>
			<id>HEAD_001</id>
			<content>Warranties and Disclaimers</content>
			<locale>en-US</locale>
		</heading>
		<children xsi:type="Section">
			<id>CLAUSE_001</id>
			<heading>
				<id>Disclaimer of Warranty</id>
				<content>EXCEPT AS EXPRESSLY PROVIDED IN THIS AGREEMENT, NEITHER PARTY PROVIDES ANY WARRANTIES, WHETHER WRITTEN OR ORAL, EXPRESS OR IMPLIED, REGARDING THE PRODUCTS FOR COMMERCIAL USE, AND EACH PARTY HEREBY DISCLAIMS ALL OTHER WARRANTIES, WHETHER WRITTEN OR ORAL, EXPRESS AND IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND FREEDOM FROM INFRINGEMENT OF THIRD PARTY RIGHTS.</content>
				<locale>en-US</locale>
			</heading>
			<pageBreak>true</pageBreak>
		</children>
		<children xsi:type="Section">
			<id>CLAUSE_002</id>
			<heading>
				<id>Contract Price.</id>
				<content>In consideration of the Equipment and the Services described in Attachment 2, the Buyer shall pay to the Seller the fixed price of $*** (the Contract Price) in accordance with the Payment Schedule and subject to the terms and conditions as set forth in this Contract. Specific quantities and prices shall be incorporated into each individual PO (the total of all such prices (as multiplied by the relevant quantities) in each PO for a given Project, a Purchase Order Price). The price of each Unit, including a pro-rata share of the Services, special installation tools and shipping fixtures with respect to each Unit and the SCADA system (collectively, the Unit Price), is set forth in Attachment 2 hereto. The currency in which the Contract Price, the Purchase Order Price or any other payments due under this Contract are stated shall be the Contract Currency..</content>
				<locale>en-US</locale>
			</heading>
			<pageBreak>true</pageBreak>
		</children>
		<children xsi:type="Choice">
			<id>OPTIONAL</id>
			<options xsi:type="Section">
				<id>CLAUSE_002</id>
				<heading>
					<id>Optional Section 001</id>
					<content>This is optional section 001.</content>
					<locale>en-US</locale>
				</heading>
				<pageBreak>true</pageBreak>
			</options>
			<options xsi:type="Section">
				<id>CLAUSE_002</id>
				<heading>
					<id>Optional Section 002.</id>
					<content>This is optional section 002.</content>
					<locale>en-US</locale>
				</heading>
				<pageBreak>true</pageBreak>
			</options>
			<required>false</required>
		</children>
		<pageBreak>true</pageBreak>
	</content>
</ContractTemplate>
```

**Comment by dselman** [comment]
Quite impressed by the commonmark JS parser. Sample [output](https://spec.commonmark.org/dingus/?text=%23%20Contract%0AThis%20is%20a%20sample%20contract%20template.%20You%20can%20introduce%20variables%2C%20like%20%5B%7Bname%7D%5D%20or%20even%20have%20static%20lists%3A%0A-%20add%20list%20items%0A-%20like%20this%0A%0A%5B%7Bif%20name%20%3E%2010%7D%5D%0AThis%20is%20a%20conditional%20section.%0A%5B%7Belseif%20name%20%3C%205%7D%5D%0AAnother%20conditional%20section.%0A%5B%7Belse%7D%5D%0AAnd%20one%20more.%0A%5B%7Bendif%7D%5D%0A%0A%23%23%20Clause%0A%0AThe%20document%20can%20contain%20**bold**%2C%20~~strike~~%2C%20_italic_%20text%20or%20even%20%5Blinks%5D(https%3A%2F%2Fclause.io).%0A%0AOr%20numbered%20lists%3A%0A1.%20Item%20one%0A1.%20Item%20two%0A%0A%23%23%23%20Sub-sub%20heading%0A%0AThis%20is%20some%20text%20formatted%20as%20code%3A%0A%0A%60define%20constant%20PI%20%3D%204.0%20*%20atan(1.0)%60%0A%0AThis%20is%20a%20quote%3A%0A%0A%3E%20Look%20before%20you%20leap!%0A%0AAnd%20this%20is%20an%20inline%20Ergo%20code%20block%3A%0A%0A%5B%7Bcode%7D%5D%0Adefine%20constant%20PI%20%3D%204.0%20*%20atan(1.0)%0A%5B%7Bendcode%5D%7D%0A%0A---%0A%23%20Page%20Two%0A%0AEven%20page%20breaks%20are%20supported!)

**Comment by dselman** [comment]
Closing, as we have moved to using extended CommonMark for serialisation.
