### ISSUE TITLE
Should template allow for lists of terms

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/cicero#20]
For instance:
```
Seller may terminate this Agreement:
(a) if Buyer fails to pay...
(b) if Buyer is in [{"material":?material}] breach...
(c) if Buyer becomes insolvent...
```

**Comment by dselman** [comment]
Another good example of this is in the volume discount template, which includes a decision table like construct.

**Comment by jeromesimeon** [comment]
I've been reviewing the volume discount template and I think
supporting an arbitrary number of rows would require a couple of
extensions to the current template format.

One extension is the ability to specify a piece of repeating text
(which would correspond to an array in the corresponding
JSON). Another extension needed is the ability to describe alternative
texts.

One possiblity that addresses both requirements is to rely on a simple
kind of regular expressions. Here is a short proposal which suggests
some new markup to do that:

Markup for optional text with corresponding JSON field:

```
[?{myOptionalField} some text goes here]
```

Markup for repeated text with corresponding JSON field:
```
[+{myArrayField} some text that will might be repeated one or more times goes here]
```

Markup for alternative texts:
```
[some left text goes here \| some right text goes here]
```

With those new constructs in mind, the decision table from the
`volumediscount` template could be written as follows:

```
Volume-Based Card Acceptance Agreement [Abbreviated]

This Agreement is by and between Card, Inc., a New York corporation, and you, the Merchant. By accepting the Card, you agree to be bound by the Agreement. 
Discount means an amount that we charge you for accepting the Card, which amount is: ...

| Annual Dollar Volume      | Discount             |
[+{discountRates}| [ Less than $[{volumeUpTo}] million \| [{volumeAbove}] million to [{volumeUpTo}] \| Greater than [{volumeAbove}] million] | [{rate}]% |]

_______________________					_____________________
 Card, Inc.								Merchant
```

Now if you parse the corresponding clause text with this template:

```
Volume-Based Card Acceptance Agreement [Abbreviated]

This Agreement is by and between Card, Inc., a New York corporation, and you, the Merchant. By accepting the Card, you agree to be bound by the Agreement. 
Discount means an amount that we charge you for accepting the Card, which amount is: ...

| Annual Dollar Volume      | Discount             |
| Less than $1 million      | 3.00%                |
| $1 million to $10 million | 2.90%                |
| Greater than $10 million  | 2.80%                |
```

It should succeed and return with the following JSON:

```
{
    'discountRates' : [
	{ 'volumeUpTo' : 1,
	  'rate' : 3.00 },
	{ 'volumeUpTo' : 10,
	  'volumeAbove' : 1,
	  'rate' : 2.90 },
	{ 'volumeAbove' : 10,
	  'rate' : 2.80 }
    ]
}
```

**Comment by jeromesimeon** [comment]
Note that something along those lines would also address issue #16 and possibly #17.

**Comment by dselman** [comment]
Like it.

**Comment by dselman** [comment]
An example that uses arrays in the model.

[latedeliveryandpenalty.zip](https://github.com/accordproject/cicero/files/2891179/latedeliveryandpenalty.zip)

**Comment by dselman** [comment]
Code that prevents using Arrays in the template model:
https://github.com/accordproject/cicero/blob/master/packages/cicero-core/src/template.js#L328

**Comment by dselman** [comment]
Current state is that you CAN use arrays in your models - but not the template model itself.

**Comment by hm2space** [comment]
It would be interesting to support any arbitrary sequence of chars as separator in arrays. 
For example, in a table like this one: 
`|   DEAL    | 16.00 | 15.90 | 15.65 | 14.75 |  13.20 | ` 
' | ' is the delimiter. 
And we can even go a step further by supporting Regex to be used as separators.

**Comment by adrianffletcher** [comment]
Attached is another example which is a fuel surcharge clause which is rather cumbersome as we have to define new model variables for each element in the table and we require a fixed number of rows in the table.

<img width="688" alt="Screen Shot 2019-05-16 at 11 44 46" src="https://user-images.githubusercontent.com/29235349/57848114-0e665080-77d0-11e9-91df-96334a3eec31.png">


[fuel-surchargev0.1.2.zip](https://github.com/accordproject/cicero/files/3186681/fuel-surchargev0.1.2.zip)

**Comment by jeromesimeon** [comment]
We now have support for lists using blocks (tied to Markdown lists), either as: `{{#ulist}} ... {{/ulist}}` or `{{#olist}} ... {{/olist}}` in version `0.20`. I'm closing. Reopen if you disagree! (Or open a new issue if new feature needed).
