### ISSUE TITLE
Execute on windows fails with \r\n problem

### ISSUE THREAD

**Issue by contractpendev** [accordproject/cicero#219]
```
10:22:31 AM - info: Compiling Ergo logic
Promise finished and result is
undefined
10:22:31 AM - error: invalid syntax at line 1 col 43:

  Name of the person to greet: "Fred Blogs".
                                            ^
Unexpected "\r"

```

I am using the Javascript API on the hello world example and have the above error.

const Commands = require('@accordproject/cicero-cli/lib/commands');
Commands.execute(templatePath, samplePath, requestsPath, statePath);

Windows newlines are \r\n, Linux are \n.

A simple fix (simple does not mean a good idea) is to in executeTemplate 
https://www.npmjs.com/package/file-normalize

```
    var sampleText = fs.readFileSync(samplePath, 'utf8');
    sampleText = file.normalizeNL(sampleText);

```

**Comment by dselman** [comment]
This sounds like a good idea. We should ensure that we are consistent everywhere we use `fs.readFileSync` that newlines are normalised. Want to work on a PR for this?

**Comment by jeromesimeon** [comment]
Duplicate  of #197

**Comment by lamqson** [comment]
Sons-MacBook-Pro:cicero sonlam$ cat sample.txt
Name of the person to greet: "Fred Blogs".
Thank you!
Sons-MacBook-Pro:cicero sonlam$ cicero --version
0.13.5
Sons-MacBook-Pro:cicero sonlam$ cicero parse --template helloworld@0.11.1.cta --sample sample.txt
4:53:46 PM - error: invalid syntax at line 3 col 0:

  
  ^
Unexpected "\n"

Sons-MacBook-Pro:cicero sonlam$

**Comment by jeromesimeon** [comment]
> Sons-MacBook-Pro:cicero sonlam$ cat sample.txt
> Name of the person to greet: "Fred Blogs".
> Thank you!
> Sons-MacBook-Pro:cicero sonlam$ cicero --version
> 0.13.5
> Sons-MacBook-Pro:cicero sonlam$ cicero parse --template [helloworld@0.11.1.cta](mailto:helloworld@0.11.1.cta) --sample sample.txt
> 4:53:46 PM - error: invalid syntax at line 3 col 0:
> 
> ^
> Unexpected "\n"
> 
> Sons-MacBook-Pro:cicero sonlam$

@lamqson This looks like a different issue to me? I'm suspecting you may have an extraneous new line in your sample? This issue was specific to `\r` which is carriage return and used as part of the new line on Windows platforms.

**Comment by lamqson** [comment]
> > Sons-MacBook-Pro:cicero sonlam$ cat sample.txt
> > Name of the person to greet: "Fred Blogs".
> > Thank you!
> > Sons-MacBook-Pro:cicero sonlam$ cicero --version
> > 0.13.5
> > Sons-MacBook-Pro:cicero sonlam$ cicero parse --template [helloworld@0.11.1.cta](mailto:helloworld@0.11.1.cta) --sample sample.txt
> > 4:53:46 PM - error: invalid syntax at line 3 col 0:
> > ^
> > Unexpected "\n"
> > Sons-MacBook-Pro:cicero sonlam$
> 
> @lamqson This looks like a different issue to me? I'm suspecting you may have an extraneous new line in your sample? This issue was specific to `\r` which is carriage return and used as part of the new line on Windows platforms.

@jeromesimeon: Thanks a lot for looking into it. I just use 'vi' to create the file. I don't see any extra \n ( I attach the file here). But I wonder the parser should be able to strip the characters? It is very hard for users to hunt for the invisible characters. Would you be able to add this request?

Best Regards,
[sample.txt](https://github.com/accordproject/cicero/files/3779968/sample.txt)

**Comment by jeromesimeon** [comment]
> > > Sons-MacBook-Pro:cicero sonlam$ cat sample.txt
> > > Name of the person to greet: "Fred Blogs".
> > > Thank you!
> > > Sons-MacBook-Pro:cicero sonlam$ cicero --version
> > > 0.13.5
> > > Sons-MacBook-Pro:cicero sonlam$ cicero parse --template [helloworld@0.11.1.cta](mailto:helloworld@0.11.1.cta) --sample sample.txt
> > > 4:53:46 PM - error: invalid syntax at line 3 col 0:
> > > ^
> > > Unexpected "\n"
> > > Sons-MacBook-Pro:cicero sonlam$
> > 
> > 
> > @lamqson This looks like a different issue to me? I'm suspecting you may have an extraneous new line in your sample? This issue was specific to `\r` which is carriage return and used as part of the new line on Windows platforms.
> 
> @jeromesimeon: Thanks a lot for looking into it. I just use 'vi' to create the file. I don't see any extra \n ( I attach the file here). But I wonder the parser should be able to strip the characters? It is very hard for users to hunt for the invisible characters. Would you be able to add this request?
> 
> Best Regards,
> [sample.txt](https://github.com/accordproject/cicero/files/3779968/sample.txt)

This file ends with a new line `\n` character. The one I used ~above~ in the other issue(!) ends with a `!` character.
