### ISSUE TITLE
Upgrade version of marked to fix vulnerability

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero#22]
Known moderate severity security vulnerability detected in marked < 0.3.7 defined in package-lock.json.package-lock.json update suggested: marked ~> 0.3.7. | Known moderate severity security vulnerability detected in marked < 0.3.7 defined in package-lock.json.package-lock.json update suggested: marked ~> 0.3.7. | Known moderate severity security vulnerability detected in marked < 0.3.7 defined in package-lock.json. | package-lock.json update suggested: marked ~> 0.3.7.

**Comment by jeromesimeon** [comment]
This issue comes from the jsdoc, the the corresponding thread (with some workarounds if we feel this is important). https://github.com/jsdoc3/jsdoc/issues/1489

**Comment by dselman** [comment]
I've updated all the dependencies and this is now fixed.
