### ISSUE TITLE
Failed to load model file when run cicero parse command

### ISSUE THREAD

**Issue by fgomezotero** [accordproject/cicero#248]
Following the official deocumentation available on the website, when I try to execute the cicero parse command within one of the templates, after cloning the cicero-template-library, specifically the Helloworld gives me the following error:

![image](https://user-images.githubusercontent.com/2965157/48947499-27bccd00-ef10-11e8-8e1f-57a099ebff29.png)

**Comment by mttrbrts** [comment]
Hi @fgomezotero thank you for opening an issue. 

For most template models, the parser tries to download imported files from the AP Model Repo (https://models.accordproject.org).

It looks like this operation failed during the SSL handshake. Do you have a firewall, or other network restriction that might stop this?

Does the following command work for you?
```
wget https://models.accordproject.org/cicero/runtime.cto
```

**Comment by fgomezotero** [comment]
It was resolved, it was a proxy problem. Thank you

**Comment by mttrbrts** [comment]
Thanks, @fgomezotero, I'll add a warning about this to the docs about this.
