### ISSUE TITLE
Template without any parameters fails to parse

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/cicero#25]
## Context
The template grammar insists that a template must have at least one parameter. 
https://github.com/accordproject/cicero/blob/edd14532b80c2c4bc2a9d16a50592c3eb5733362/packages/cicero-core/lib/tdl.ne#L67

This means that clauses which only require request data, or are otherwise 'dumb' are not valid.

## Expected Behavior
The following clause grammar should parse successfully:
```This is a dumb clause with no template parameters```

## Actual Behavior
```
mattmbp:integration-demo-xeroviazapier matt$ cicero parse --template ./ --dsl ./sample.txt 
09:27:53 - info: Logging initialized. 2018-02-08T09:27:53.307Z
09:27:54 - error:  Error: invalid syntax at line 1 col 1:

  This clause transforms a generic payment into an invoice that will be raised in a private Xero account. The integration happens via Zapier.
  ^
Unexpected LastChunk token: "This clause transforms a generic payment into an invoice that will be raised in a private Xero account. The integration happens via Zapier.\n"

    at Parser.feed (/Users/matt/.nvm/versions/node/v8.9.3/lib/node_modules/cicero-cli/node_modules/nearley/lib/nearley.js:320:23)
    at Template.buildGrammar (/Users/matt/.nvm/versions/node/v8.9.3/lib/node_modules/cicero-cli/node_modules/cicero-core/lib/template.js:138:16)
    at template.getModelManager.updateExternalModels.then (/Users/matt/.nvm/versions/node/v8.9.3/lib/node_modules/cicero-cli/node_modules/cicero-core/lib/template.js:793:26)
    at <anonymous>
```

## Possible Fix
Change the nearley grammar to allow zero or more items, rather than one or more.
Also be careful not to allow completely empty templates
https://github.com/accordproject/cicero/blob/edd14532b80c2c4bc2a9d16a50592c3eb5733362/packages/cicero-core/lib/tdl.ne#L67

## Existing issues
None.

## Your Environment
* Version used: cicero release 0.2.28
* Environment name and version (e.g. Chrome 39, node.js 5.4): node 8.9.3
* Operating System and version (desktop or mobile): macOS High Sierra

**Comment by jeromesimeon** [comment]
👍 

```
bash-3.2$ cat models/model.cto 
namespace org.accordproject.helloworld

transaction Request {
  o String input
}

transaction Response {
  o String output
}

/**
 * The template model
 */
@AccordTemplateModel("helloworld")
concept TemplateModel {
}

// this is a change!
bash-3.2$ cat grammar/template.tem 
Name of the person to greet: .
Thank you!
bash-3.2$ cat sample.txt 
Name of the person to greet: .
Thank you!bash-3.2$ cicero execute 
08:07:55 - info: Logging initialized. 2018-05-16T12:07:55.899Z
08:07:56 - info: Using current directory as template folder
08:07:56 - info: Loading a default sample.txt file.
08:07:56 - info: Loading a single default request.json file.
08:07:56 - info: Loading a default state.json file.
08:07:56 - info: {"clause":"helloworld@0.0.5-1a250b9a7a80af2d9a6ebdbd69cf69b8b62272870fb2f94da3c00efbdca33244","request":{"$class":"org.accordproject.helloworld.Request","input":"Accord Project"},"response":{"$class":"org.accordproject.helloworld.Response","output":"Hello undefined Accord Project","transactionId":"d69bcc04-0a87-4980-8b17-63a6c8bf796b","timestamp":"2018-05-16T12:07:56.574Z"},"state":{"$class":"org.accordproject.common.State","stateId":"org.accordproject.common.State#1"},"emit":[]}
```

**Comment by jeromesimeon** [comment]
@mttrbrts Should we allow templates with no logic in that case?

**Comment by mttrbrts** [comment]
Yes, eventually I can see a need for reusable non-computable clauses templates. However, for now, we can capture these use cases with prose in a contract template. 

Perhaps we represent the logic of non-computable clauses as (auto-generated) identity functions?

**Comment by dselman** [comment]
Yes, we want to support logic-less templates for document assembly etc

**Comment by jeromesimeon** [comment]
I like the auto-generated idea. It shouldn't be too hard to do.
