### ISSUE TITLE
Strings have to be enclosed in double quotes

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero#3]
Need to think about how we represent strings in the generated grammar. At present, by default, all strings must be enclosed in double quotes, which is confusing for lawyers.

E.g. `"Party A" will be deemed to` in the template https://templates.accordproject.org/acceptance-of-delivery@0.2.0.html

The Nearley grammar that is generated based on this template:
https://github.com/accordproject/cicero/blob/master/packages/cicero-core/lib/template.ne#L75

**Comment by jeromesimeon** [comment]
This issue is discussed in more details in #305
