### ISSUE TITLE
Cicero to allow different date formats to be specified

### ISSUE THREAD

**Issue by jphillips-bp3** [accordproject/cicero#300]
We have a need to provide US date formats in a template, and in this case an the dates format specified in the contract is "May 1, 2019", so `month-name day, year` if using the RFC2822 Date and Time format specification: https://tools.ietf.org/html/rfc2822#section-3.3

This is also related to this issue: https://github.com/accordproject/cicero/issues/63

**Comment by jeromesimeon** [comment]
Addressed with new Date/Time parsing support in Cicero 0.12.

**Comment by jeromesimeon** [comment]
Demoed here in Template Studio:
<img width="636" alt="Screen Shot 2019-04-05 at 1 13 26 AM" src="https://user-images.githubusercontent.com/670099/55604912-21512400-5740-11e9-881c-0a7d4171ad5c.png">

With the template grammar:
<img width="673" alt="Screen Shot 2019-04-05 at 1 13 38 AM" src="https://user-images.githubusercontent.com/670099/55604917-23b37e00-5740-11e9-9129-be005e491226.png">

**Comment by jeromesimeon** [comment]
@jphillips-bp3 Can we close this?

**Comment by jphillips-bp3** [comment]
@jeromesimeon I have not tried it but happy to close the ticket.

**Comment by jeromesimeon** [comment]
Thanks, I'll close. Feel free to reopen or open a new issue if you have problems with the feature as implemented.
