### ISSUE TITLE
String parameters should not be quoted

### ISSUE THREAD

**Issue by jphillips-bp3** [accordproject/cicero#305]
So a scenario has come up with the client I am working with, in that they want one of the terms used in the clause template text to be editable. It is not feasible to split the clause into two and have this as static text in between because the variable text is embedded within the clause, which itself is atomic.

The text is as follows:

> Transportation Company’s **Rates** contain fuel costs...

Where the term `Rates` may be different for different parties using the clause.

The suggestion here for the moment is that we use a template variable so it can be changed, but this is not ideal. From a visual point of view, because this is a String, the term needs to be wrapped in quotes, so in the clause it reads as:

> Transportation Company’s "Rates" contain fuel costs...

And from a standards point of view, having this as a contract variable just doesn't feel right.

You have probably thought of this before, but do you have any thoughts as to how we might tackle this situation properly? I wondered if in the template we could have an editable text declaration, for example:

>  Transportation Company’s [{text as editable}] contain fuel costs...

Therefore, the template engine would allow anything to be inserted in between the words `Company’s ` and ` contain` without quotes.

**Comment by dselman** [comment]
I think this really _is_ a string parameter for the template. What we need to work on is removing the need to enclose string parameters in quotes.

**Comment by jphillips-bp3** [comment]
> I think this really _is_ a string parameter for the template. What we need to work on is removing the need to enclose string parameters in quotes.

Yes, the quotes is the main problem here.

**Comment by jeromesimeon** [comment]
One of the issues with not quoting is ambiguity. What do you expect the output to be in a case where the template says:
```
This is a contract for [{client}] [{address}]
```

and the sample says:
```
This is a contract for Frank Smith 555 Main Street
```

to be?

**Comment by dselman** [comment]
In theory Nearly will produce two (N!) ASTs for that so we can at least detect an ambiguous template - and force the user to insert some text in the template to separate the strings. You are right that there are probably performance and usability issues however.

**Comment by jeromesimeon** [comment]
We can provide guidelines to template developers, but this is something to consider. In this particular example, one of the issue from a performance standpoint (with a Nearly-like parser) is that you get a combinatorial number of parses (N!).

**Comment by jeromesimeon** [comment]
Note: generateText will still work great.

**Comment by jphillips-bp3** [comment]
> ...and force the user to insert some text in the template to separate the strings.
I think that is reasonable, at the end of the day if you want adjacent String variables then the template design should combine them into one.

**Comment by jeromesimeon** [comment]
I think this works, with the assumption that you work with the smallest match, but it will be interesting how to do that with Nearly.

Here is a not so clear example. Template:
```
This is a contract for [{client}]@[{address}]
```
with the sample:
```
This is a contract for John @ Home @ john@foobar.io
```

We could fairly easily reject when there are multiple parses, with a bit of extra complexity on providing good error messages.

**Comment by jeromesimeon** [comment]
Parsing still requires quotes to disambiguate. Editing using the Contract Editor, or pdf generation now support without quotes.
