### ISSUE TITLE
Is there a way of passing the clause transaction Id to the Payment Obligation event?

### ISSUE THREAD

**Issue by jphillips-bp3** [accordproject/cicero#307]
In the demo I am building, I am listening for payment obligation events so I can update the clause response I am displaying on the UI with the correct payment obligation.

So is there a way of passing through the clause transaction Id from the clause being executed to the Payment Obligation being emitted? Is this transaction Id available from within the clause itself?

I guess I could generate a transaction Id and pass this into the clause and then through to the payment obligation, but if there was a built in capability to do this that would be better to use.

**Comment by jeromesimeon** [comment]
The transactionId is not visible on the logic side. I think the reason being that it has to be generated outbound-side through validation (possibly something which could be changed through a `uuid()` function in Ergo, but this makes the logic a lot more complicated throughout).

I'm a bit unclear on a couple of things:
- Aren't the response and the emitted obligation returned together?
- Wouldn't the `contractId` attached to the obligation be sufficient?

If not, I would indeed add a logical identifier in the request and pass it through to correlate the result.

**Comment by jphillips-bp3** [comment]
@jeromesimeon No the PO is not returned in the response. I am receiving it because I have set up a custom HTTP action against the clause which calls back to my Node-RED server.

But you have given me the idea of just bolting the PO object into the response, that way I don't need to listen for an asynchronous event. For the purposes of this demo that would be fine and would reduce the complexity. The PO would still be emitted for the payment process to hang off.

**Comment by jeromesimeon** [comment]
That makes sense.
