### ISSUE TITLE
Remove the ability to package Nearley grammar 

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero#308]
Cicero currently allows your to write an entire Nearley grammar by hand for a template and package it instead of a `template.tem` file. We should remove this capability for compatibility and security reasons. I don't believe it is documented or used outside of tests.

**Comment by jeromesimeon** [comment]
This also makes templates non-portable and JavaScript dependent. I'm listing this as part of  the "Deprecate JavaScript" project.

**Comment by jeromesimeon** [comment]
Implemented in 0.12
