### ISSUE TITLE
Support for Template Display Name

### ISSUE THREAD

**Issue by thisaac** [accordproject/cicero#388]
It appears there's no way to add spacing or alternate casing to the `name` of a template. This suggests that the name is more of an identifier rather than a display name. 

This especially becomes an obstacle when displaying multiple templates (cf. [Accord Template Library](https://templates.accordproject.org/)) and trying to help people distinguish quickly between the contract clauses in a list.

Could one solution could be to add a display name to the metadata?

**Comment by irmerk** [comment]
Yes, this is a great suggestion. We will be discussing this during the tech working group call this Wednesday.

**Comment by jeromesimeon** [comment]
> Yes, this is a great suggestion. We will be discussing this during the tech working group call this Wednesday.

Correction: I'm expecting this to be on the agenda for the following week.

**Comment by mttrbrts** [comment]
As per the discussion yesterday on the working group call, https://vimeo.com/350070645

- The name of this metadata property is `displayName`.
- The property should be a JavaScript string which allows it to be persisted to a template's `package.json` file. This gives us a lot of flexibility to include unicode characters, emojis etc. However it means that we should adopt JavaScript single character escape sequences e.g. `\b`,`\n`,`\"` etc.
- The length of the property should be constrained to avoid it being used as a description field. I propose `214` characters to align with the `package.json` limit for package names.
- Internationalization should follow the current convention with templates which is that templates have a single locale and are not dynamic to a user's locale. Templates that are the same except for localization are duplicated currently. Localization is discussed further in issue #174

**Comment by jeromesimeon** [comment]
Couple of comments:
- Internally, this should probably be added to the `cicero-core.Metadata` module.
- We may want to have an API call that lets a user set the `displayName` programmatically, and which makes sure exporting to an archive result in a `package.json` with the new name
- Have we checked if there is a standard `package.json` documented field which would be appropriate?

**Comment by mttrbrts** [comment]
I can't find a standard `package.json` field that performs the same function

**Comment by mttrbrts** [comment]
Also, we don't currently provide a way to change the template name, instead this is immutable via the API once the `template` class is instantiated. The `template` constructor sets the template name via `packageJson` object. I suggest that we do the same for `displayName`.
