### ISSUE TITLE
Support for different formats for Monetary Amounts

### ISSUE THREAD

**Issue by adrianffletcher** [accordproject/cicero#389]
I would like to be able to specify a Monetary Amount using a format '$10,000,000' or '$10m' for convenience.

**Comment by jeromesimeon** [comment]
This could use a similar approach as to what is used for formatting of `DateTime` values.

**Comment by AaronCGoidel** [comment]
I could look into this. 

I imagine that the useful formats would be as follows. Does anything else come to mind?
- Numerical ($10,000,000)
- Abbreviated ($10m)
- Text ($10 million)

**Comment by jeromesimeon** [comment]
@AaronCGoidel That would be great. I don't have insights as to common format, maybe @adrianffletcher does. I would love to see a proposal which can be flexible, maybe with an idea similar to what we are doing for `DateTime` types.

For those, you can write `{{myDate as "FORMAT"}}` where `FORMAT` can be built using a syntax documented here: https://docs.accordproject.org/docs/ref-markup.html#datetime-formats

For something like this, it might be worth having a written proposal in GitHub (in this issue) first.

**Comment by mttrbrts** [comment]
@AaronCGoidel @jeromesimeon , I've been looking at `Dinero` as a possible future backend for native monetary amount calculations. We could expose the same formatting options here: https://sarahdayan.github.io/dinero.js/module-Dinero.html#~toFormat

**Comment by jeromesimeon** [comment]
> @AaronCGoidel @jeromesimeon , I've been looking at `Dinero` as a possible future backend for native monetary amount calculations. We could expose the same formatting options here: https://sarahdayan.github.io/dinero.js/module-Dinero.html#~toFormat

I'm not sure I like that direction which may imply having a new `MonetaryAmount` type directly built into Concerto. I would much prefer adding support for a native arbitrary precision type (e.g., either as a new semantics for `Integer` or as a new type `Decimal`) with the benefit that those could be used for other things than monetary amounts.

**Comment by dselman** [comment]
Also worth noting that (like dates) formatting of numbers is locale dependent.

**Comment by jeromesimeon** [comment]
> @AaronCGoidel @jeromesimeon , I've been looking at `Dinero` as a possible future backend for native monetary amount calculations. We could expose the same formatting options here: https://sarahdayan.github.io/dinero.js/module-Dinero.html#~toFormat

As an addendum I do like the format support :)

**Comment by AaronCGoidel** [comment]
> @AaronCGoidel what is the status of this? I'm opening it back up in the meantime.
 
@irmerk I've started creating a template, though it is midterm season so I'm a little backlogged. Feel free to open this back up in the meantime, anyone who has a little more time and thinks that they want to take a crack at this is totally free to do so. Sorry that I can't give this the attention it needs at the moment.

**Comment by irmerk** [comment]
@AaronCGoidel no worries! Come to it when you have time and good luck on midterms.

**Comment by jeromesimeon** [comment]
@AaronCGoidel Any progress on this?

**Comment by jeromesimeon** [comment]
> @AaronCGoidel @jeromesimeon , I've been looking at `Dinero` as a possible future backend for native monetary amount calculations. We could expose the same formatting options here: https://sarahdayan.github.io/dinero.js/module-Dinero.html#~toFormat

@mttrbrts I'm looking at this as well right now. Currently I'm only focused on formatting, adding the following kind of support in Cicero: `{{amount as "FORMAT"}}` where format could be along the lines of what we have for date and time.

I actually like the idea of being able to specify the format including the currency code. It could look along those lines (For a sample monetary amount `MonetaryAmount{ value: 1400.99, currencyCode: USD }`).

| Input | Example |
| 0,0.00 | 1,400.99 |
| 0,0.0 | 1,400.9 |
| 0 0,00 | 1 400,9 |
| CCC | USD |
| C | $ |

There are quite a number of questions there:
- Should we use the Dinero format "as is" instead
- Should the ability to use different separators (e.g., `,` instead of `.` and ` ` instead of `,`) be part of the format or a reflection of the localization
- What should we do about rounding?
- Do we want a format that can handle large sums (e.g., `$3.59 Billion`)

Some of those ideas came out of an earlier discussion with @martinhalford.

## Examples

```
{{amount as "0,0.000 CCC"}} -> 1,400.990 USD
{{amount as "C0,0.000"}} -> $1,400.990
{{amount as "0 0,0"}} -> 1 400.9$
```

**Comment by mttrbrts** [comment]
Dinero is very small, 9.8Kb https://bundlephobia.com/result?p=dinero.js@1.8.0,

I suggest that we adopt exactly the same format, we should even propose changes upstream if we want to extend the format. The repo seems very active

**Comment by jeromesimeon** [comment]
Possibly useful details on symbols, not sure how authoritative this is. https://en.wikipedia.org/wiki/Currency_symbol

**Comment by jeromesimeon** [comment]
> Dinero is very small, 9.8Kb https://bundlephobia.com/result?p=dinero.js@1.8.0,
> 
> I suggest that we adopt exactly the same format, we should even propose changes upstream if we want to extend the format. The repo seems very active

One of the questions when taking up a library like this is how portable this is (we would have to re-implement some of it in e.g., Java or WASM or ...).

**Comment by mttrbrts** [comment]
Also see this note: 

> toFormat wraps around Number.prototype.toLocaleString. For that reason, format will vary depending on how it's implemented in the end user's environment.

https://dinerojs.com/module-dinero#~toFormat

We may be able to do what we want natively. Even more reason not to deviate

**Comment by jeromesimeon** [comment]
> Also see this note:
> 
> > toFormat wraps around Number.prototype.toLocaleString. For that reason, format will vary depending on how it's implemented in the end user's environment.
> 
> https://dinerojs.com/module-dinero#~toFormat
> 
> We may be able to do what we want natively. Even more reason not to deviate

Another caveat: I think this means the output format will be US(?) centric until we have proper localisation support in Cicero.

**Comment by jeromesimeon** [comment]
@mttrbrts Another consideration: whatever format we support we have to be able to parse as well.

**Comment by dselman** [comment]
I would also look at MS Excel and Google Sheets for inspiration for formatting strings. 

https://support.office.com/en-us/article/review-guidelines-for-customizing-a-number-format-c0a1d1fa-d3f4-4018-96b7-9c9354dd99f5

https://developers.google.com/sheets/api/guides/formats

**Comment by dselman** [comment]
The Unicode CLDR is also a good reference:
https://github.com/globalizejs/globalize

Browser support for locale specific formatting (but no parse!)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

**Comment by martinhalford** [comment]
> > Also see this note:
> > > toFormat wraps around Number.prototype.toLocaleString. For that reason, format will vary depending on how it's implemented in the end user's environment.
> > 
> > 
> > https://dinerojs.com/module-dinero#~toFormat
> > We may be able to do what we want natively. Even more reason not to deviate
> 
> Another caveat: I think this means the output format will be US(?) centric until we have proper localisation support in Cicero.

Don't think we can launch with US format support only. Would need some workaround for local currencies.

**Comment by jeromesimeon** [comment]
PR in #527 supports the following formats for amounts (of type `Double`):

```
0x0y0
0x0y00
0x0y000
```
Where `x` and `y` is any individual character. `x` (resp. `y`) is used as delimiter between every digits in the whole number part (resp. delimiter between the whole number part and the decimal part).

The number of `0` after the second separator is used to determine the number of digits kept in the fractional part of the amount (from 1 to 3 digits).

It also supports the following two formatting directives for monetary amounts (of type `org.accordproject.money.MonetaryAmount`:
- `CCC` for ISO currency codes
- `K` for monetary symbols

The format can also contains any other text, including whitespace, but not new lines. e.g., `CCC 0,0.0 (K)`.

The format can be used:
- in the template grammar using the syntax `{{variableName as "FORMAT"}}` when the variable `variableName` has a type which supports a format.
- in Ergo logic using the syntax `expr as "FORMAT"`  when the expression `expr` has a type which supports a format.

### Examples

```
45100.99 as "0,0.0" --> 45,101.0"
45100.99 as "0,0.00" --> 45,100.99"
45100.99 as "0,0.000" --> 45,100.990"

MonetaryAmount{ currencyCode: USD, amount: 45100.99 } as "CCC 0,0.0" --> USD 45,101.0
MonetaryAmount{ currencyCode: AUD, amount: 45100.99 } as "0,0.0 (CCC)" --> 45,101.0 (AUD)
MonetaryAmount{ currencyCode: PLN, amount: 45100.99 } as "K0,0.0 (CCC)" --> zł45,101.0 (PLN)
```

### Notes

- There can only be one amount description in the format (i.e., `0,0.0 / 0 0,0` is an error)
- The currency symbol and the currency code have to be consistent or an error is raised (i.e., `zł45,101.0 (AUD)` is not a valid instance for `"K0,0.0 (CCC)"`

**Comment by dselman** [comment]
Awesome. Great work.

**Comment by jeromesimeon** [comment]
I'm closing this as done. Please reopen if you feel this isn't completely resolved.
