### ISSUE TITLE
problem with test coverage importing cicero package

### ISSUE THREAD

**Issue by j4m3sb0mb** [accordproject/cicero#401]
When I import a cicero package and run test coverage on my application with jest, jest tries to do coverage on this folder: /home/travis/build/accordproject/cicero/packages/cicero-core/src but it tells me that coverage is 0 for these files.
this is only few files but the list is long:

travis/build/accordproject/cicero/packages/cicero-core/src                     |     9.76 |     0.77 |        0 |     9.87 |                   |
  clause.js                                                                     |      100 |      100 |      100 |      100 |                   |
  datetimeformatparser.js                                                       |     4.88 |        0 |        0 |     4.88 |... 10,112,113,115 |
  errorutil.js                                                                  |     7.69 |        0 |        0 |     9.09 |... 30,31,33,34,36 |
  grammarvisitor.js                                                             |    14.29 |        0 |        0 |    14.29 |... 14,225,226,236 |
  metadata.js                                                                   |     6.82 |        0 |        0 |      6.9 |... 12,321,322,323 |
  
I think the problem is related to a cicero and ergo nyc configuration:

"produce-source-map": "true",
"sourceMap": "inline",

in package.json#nyc

I can't understand why are you using inline source maps for test coverage and why it should stay in the npm module

**Comment by j4m3sb0mb** [comment]
in `node_modules/@accordproject/cicero-core` every file has coverage inline source map with path like this: `/home/travis/build/accordproject/cicero/packages/cicero-core/src/contract.js`
but in my pc there isn't this file.
I think that this is causing errors in my coverage tests because in the coverage report is written that cicero-core files are not tested.

**Comment by mttrbrts** [comment]
Hi @j4m3sb0mb , thanks for your report, I'll take a look

**Comment by mttrbrts** [comment]
@j4m3sb0mb we're merged a change that addresses this issue. It will be included in the next release that we make, however in the meantime you can test the change by using the `unstable` release.
```
npm i -g @accordproject/cicero-core@unstable
```

Let us know how you get on, and we've love to hear about what you're building in a Technology Working Group call, https://www.accordproject.org/working-groups/technology

**Comment by jeromesimeon** [comment]
A note on “unstable”. Those change quite often. You may want to look at the latest Tagged release on npmjs and explicitly use that instead. It should look like cicero-cli-20190807.....

**Comment by j4m3sb0mb** [comment]
thanks, I'll try it and let you know

**Comment by mttrbrts** [comment]
Hi @j4m3sb0mb, did this resolve your issue, please?
