### ISSUE TITLE
cicero command line model error when running in a windows powershell

### ISSUE THREAD

**Issue by DeweyWald** [accordproject/cicero#408]
When I run cicero parse or archive I get a model error every time. I upload the same code to Template Studio and if validates and I can create a CTA from template studio.

The error:
cicero archive --template rideshare-driver-requirements-service --archiveFile rideshare-driver-requirements-service
11:05:53 AM - error: Failed to find an asset that extends org.accordproject.cicero.contract.AccordClause in rideshare-driver-requirements-service. The model for the template must contain a single asset that extends org.accordproject.cicero.contract.AccordClause.

Environment
Windows 10
Cicero 0.13.3
Node 11.10.0
CTA file attached in zip file (.cta renamed to .zip)
[rideshare-driver-requirements-service (1).zip](https://github.com/accordproject/cicero/files/3570919/rideshare-driver-requirements-service.1.zip)

**Comment by jeromesimeon** [comment]
A few preliminary notes for triage:
- I was above to test and run parse on the archive on MacOs and template studio without problem. So it is indeed most likely a Windows issue.
- The error message is also consistent with the `model.cto` file not being found. It points to a possible issue with Windows file system access.
- There is at least one other possibly related Windows issue #207 

I don't know if anyone has easy access to a Windows setup (I don't) and would be able to contribute a fix for this? Help would be appreciated!

**Comment by jeromesimeon** [comment]
@DeweyWald As additional information it might be worth trying out:
1. place the template in a windows directory without whitespace (e.g., `C:\tmp\test`)
2. run Cicero with an explicit template path `cicero parse --template C:\tmp\test`

**Comment by DeweyWald** [comment]
same result

**Comment by mttrbrts** [comment]
Hi @DeweyWald, we've made an update that fixes this issue. The issue hasn't been released yet, but in the meantime you can test it with 
 ```
npm i -g @accordproject/cicero-cli@0.13.5-20190920123630
```

**Comment by DeweyWald** [comment]
This is great Matt, thanks, I will try it out.

**Comment by jeromesimeon** [comment]
This should now be fixed with Cicero 0.13.5. Could you please confirm?

**Comment by DeweyWald** [comment]
Confirmed, works great.
