### ISSUE TITLE
Ergo execution deserializes the request

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/cicero#41]
Currently, Jura scripts called from within Cicero are passed a deserialized request before execution. Maybe it shouldn't. Here is the corresponding code:
```
const code = `
        __dispatch(data,request);
        function __dispatch(data,request) {
            // Jura dispatch call
            let context = {this: data, request: serializer.toJSON(request), this: data, now: moment()};
            return serializer.fromJSON(dispatch(context));
        } 
        `;
```
inside the `buildJuraDispatchFunction`.

This may require making the Jura runtime robust to the internal representation for CTO concepts (e.g., for matching against a class or navigating relationships).

**Comment by mttrbrts** [comment]
@Jerome, can this be closed now?

**Comment by jeromesimeon** [comment]
Maybe it should be closed but then re-opened in Ergo since that behavior has been moved in the wrapper functions:
https://github.com/accordproject/ergo/blob/9cc1394f669ca01763ae98c31e236366ec935cd2/mechanization/Translation/ErgoCalculustoJavaScriptCicero.v#L67

**Comment by jeromesimeon** [comment]
This question does not arise in Cicero anymore, but is subsumed by https://github.com/accordproject/ergo/issues/157 on the Ergo side.
