### ISSUE TITLE
peerDependency Status

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero#410]
This is to track the discussion on the possibility of making `cicero` into a `peerDepencency`.

Conversation points so far from @mttrbrts, @DianaLease, and @jeromesimeon:
- [Reference material as guidance](https://blog.angularindepth.com/npm-peer-dependencies-f843f3ac4e7f)
- This would meet the guideline "_The dependency is visible in your interface_” because using templates, parsing, etc is a large part of the UI
- Being a `peerDependency` may allow for better tracking dependency versions for synchronization
- Benefit of switching to `peerDependency` is that `cicero` is used both as a direct dependency in services and an indirect dependency in the same services as well as `cicero-ui`
- Maybe have as a `peerDependency` in `cicero-ui` only? It will affect third parties importing `cicero-ui`
- Third party services could be using different `cicero` versions, so this will make a difference

**Comment by jeromesimeon** [comment]
Cicero being a peer dependency should be a decision for projects that consume it. Not sure there is anything that needs to happen from a Cicero standpoint.

**Comment by irmerk** [comment]
> Cicero being a peer dependency should be a decision for projects that consume it. Not sure there is anything that needs to happen from a Cicero standpoint.

Should this be moved into Cicero-UI?

**Comment by jeromesimeon** [comment]
> > Cicero being a peer dependency should be a decision for projects that consume it. Not sure there is anything that needs to happen from a Cicero standpoint.
> 
> Should this be moved into Cicero-UI?

I think so, or to the most relevant project where the question of whether to have Cicero as peer dependency is.

**Comment by irmerk** [comment]
Closing in favor of [Cicero UI Issue 140](https://github.com/accordproject/cicero-ui/issues/140)
