### ISSUE TITLE
Release Notes (v0.20)

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero#412]
## Tasks
- This will track and construct the overall release notes for this repo in relation to the `v0.20` project

## Related Issues:
- #346 
- #392 
- [Ergo Issue 646](https://github.com/accordproject/ergo/issues/646)

**Comment by jeromesimeon** [comment]
- Markdown based parsing and text generation
- New syntax for templates (e.g., `{{foo}}` `{{#if forceMajeure}}...{{/if}}`
- Dynamic templates (e.g., `{{% rate * 1.24 %}}`
- Based on new modelling package Concerto `0.80.*`
- ...

**Comment by irmerk** [comment]
# Cicero v0.20 :butterfly:

### This release is a full redesign of the Accord Project template technology:

- Support for Rich Text annotations with Markdown
  - Based on [CommonMark][common]
- New syntax for templates variables
- A notion of _template blocks_
  - Handles structured data such as lists or complex objects
- A new notion of _dynamic templates_
  - Allows users to create text dynamically through embedded Ergo expressions

It also includes several new Ergo features and numerous bug fixes.

**Note**: _This release requires changes to application and template code ..._

### 🚀 New Features

- #405: Support for markdown with rich text annotations (@jeromesimeon)
- #392: Fully redesigned and more expressive template syntax (@jeromesimeon)
- #346: Ability to embed Ergo expressions within your templates (@jeromesimeon)
- #435: Templates have a new directory structure, aligning better with the Accord Project conceptual model (@jeromesimeon)
- Support for lists of terms 

### 🛰 New Command Line

#425: A new and improved command line for Cicero which better aligns with the rest of the Accord Project (@jeromesimeon)
```
cicero <cmd> [args]

Commands:
  cicero parse       parse a contract text
  cicero draft       create contract text from data
  cicero normalize   normalize markdown (parse & redraft)
  cicero trigger     send a request to the contract
  cicero invoke      invoke a clause of the contract
  cicero initialize  initialize a clause
  cicero archive     create a template archive
  cicero compile     generate code for a target platform
  cicero get         save local copies of external dependencies

Options:
  --version      Show version number                                   [boolean]
  --verbose, -v                                                 [default: false]
  --help         Show help                                             [boolean]
```

### :butterfly: Ergo

- #392: New syntax for constructing strings with embedded expressions`` `This is text with {{% expression %}} and more text` `` (@jeromesimeon)
- [#3][ergo143]: Support for enumerated values, with proper typing and pattern matching (@jeromesimeon)
- [#143][ergo143]: New `set state.NAME = EXPR;` statement for modifying a specific variable in the contract state (@jeromesimeon)
- [#303][ergo303]: Redefining a constant is now a compiler warning (@jeromesimeon)

### :butterfly: Ergo Standard Library

- New functions for URI encoding (`encode` and `decode`)
- New `format` function for `DateTime`
- New `getOptions` function which returns global static options for the compiler

### 🐛 Bug Fixes

- #441, #353: Fixes to template parsing in the presence of special characters (e.g., `\t`) (@jeromesimeon)
- #407: Template variables starting with `as` do not result in parse errors anymore (@jeromesimeon)
- #406: Fixes a regression when using `DateTime` within template variables of a complex type (@jeromesimeon)
- #390: Now text generation properly handled nested clauses (@jeromesimeon)
- #375: Badly specified dates now produce an error rather than a warning (@jeromesimeon)
- [#642][ergo642]: `now` is no longer a magic variable (@jeromesimeon)
- [#575][ergo575]: `toString` now properly format numeric values based on their types (@jeromesimeon)
- [#465][ergo465]: Constants are now properly imported and scoped, and can be accessed using an explicit namespace (@jeromesimeon)
- [#644][ergo644]: Cicero compilation target properly includes type hierarchy (@jeromesimeon)
- [#645][ergo645]: Type soundness of match expression (@jeromesimeon)

[common]: https://commonmark.org/
[ergo3]: https://github.com/accordproject/ergo/issues/3
[ergo143]: https://github.com/accordproject/ergo/issues/143
[ergo303]: https://github.com/accordproject/ergo/issues/303
[ergo642]: https://github.com/accordproject/ergo/issues/642
[ergo575]: https://github.com/accordproject/ergo/issues/575
[ergo465]: https://github.com/accordproject/ergo/issues/465
[ergo644]: https://github.com/accordproject/ergo/issues/644
[ergo645]: https://github.com/accordproject/ergo/issues/645
