### ISSUE TITLE
Basic tutorial throws error

### ISSUE THREAD

**Issue by lhcneto** [accordproject/cicero#419]
I'm getting an error while following the basic tutorial to the letter, i already tried some minor variations to adress the erros, but without success.

I'm really excited about the project, just need to get started. If you could fix the tutorial or include some missing step would be great.

Below follows a detailed description of the steps I took and the error I got, as well as versions of the library.

Many thanks in advance!

Running the commands:
npm install -g @accordproject/cicero-cli
cicero --version //prints "0.13.4"
npm install -g yo 
npm install -g @accordproject/generator-cicero-template
npm install @accordproject/ergo-cli -g
ergoc --version //prints "The Ergo compiler, version 0.9.4"

node --version// prints "v10.16.0"

downloading the file "helloworld@0.11.1" or the file "helloworld@0.10.1"

and running the command:
cicero parse --template helloworld.cta --sample sample.txt 

On file copied directly from the tutorial:
"Name of the person to greet: "Fred Blogs".
Thank you!
"

throws the error:
"error: invalid syntax at line 1 col 43:

  Name of the person to greet: "Fred Blogs".
                                            ^
Unexpected "\r""

**Comment by jeromesimeon** [comment]
This should now be fixed with Cicero 0.13.5. Could you please confirm?

**Comment by lilychau1** [comment]
> This should now be fixed with Cicero 0.13.5. Could you please confirm?

I'm facing a similar issue, but having the 'Unexpected "\n"' error on line 3 (seems that when it reads the txt file, it somehow reads an extra new line when it reaches the end of the file). I double checked my sample.txt, no extra line was at the end and the version I used is up to date for both the cta and txt files.

**Comment by jeromesimeon** [comment]
Hi @lilychau1 I'm not completely sure. Could you please post your `sample.txt` here?

One thing I noticed when testing on Windows: some popular editors (e.g., Atom) have setting to remove whitespace (trailing whitespace, trailing new lines, etc). I found it difficult to identify parsing issues with those settings on.

**Comment by jeromesimeon** [comment]
> Hi @lilychau1 I'm not completely sure. Could you please post your `sample.txt` here?
> 
> One thing I noticed when testing on Windows: some popular editors (e.g., Atom) have setting to remove whitespace (trailing whitespace, trailing new lines, etc). I found it difficult to identify parsing issues with those settings on.

Just in case, for Atom directions to those settings can be found here: https://stackoverflow.com/questions/30403150/atom-text-editor-remove-trailing-whitespace-on-save

**Comment by lilychau1** [comment]
[sample.txt](https://github.com/accordproject/cicero/files/3652992/sample.txt)
Hi @jeromesimeon . Thanks for your reply. I've attached sample.txt here and I'm using Linux.

**Comment by lilychau1** [comment]
> [sample.txt](https://github.com/accordproject/cicero/files/3652992/sample.txt)
> Hi @jeromesimeon . Thanks for your reply. I've attached sample.txt here and I'm using Linux.

Actually when I use Visual Studio Code to generate the text file it goes fine. Thanks for your help! but still I'm not quite sure why it gives such difference?
[sample2.txt](https://github.com/accordproject/cicero/files/3653042/sample2.txt)

**Comment by jeromesimeon** [comment]
hi @lilychau1 The issue you are having is different from the one reported in this issue which has to do with carriage return characters `\r` (usually a Windows artefact).

I've looked at your sample and it has an extra new line `\n` at the end which is not in the template grammar, so you should make sure your sample does not have that new line. Here is a sample that should work:

[sample3.txt](https://github.com/accordproject/cicero/files/3653079/sample3.txt)

```
bash-3.2$ cicero --version
0.13.5
bash-3.2$ cicero parse --template helloworld@0.11.1.cta --sample sample.txt
10:46:12 - error: invalid syntax at line 3 col 0:

  
  ^
Unexpected "\n"

bash-3.2$ cicero parse --template helloworld@0.11.1.cta --sample sample2.txt
10:46:15 - error: invalid syntax at line 3 col 0:

  
  ^
Unexpected "\n"

bash-3.2$ cicero parse --template helloworld@0.11.1.cta --sample sample3.txt
10:46:18 - info:
{
  "$class": "org.accordproject.helloworld.HelloWorldClause",
  "clauseId": "4151ac01-f685-4678-8d86-466c8e3f03b0",
  "name": "Fred Blogs"
}
```

(note that the two samples you attached are identical)

**Comment by lilychau1** [comment]
@jeromesimeon Thanks for the answer. Though I've checked with text editor both are without an extra line and the second file actually worked fine in my machine with Cicero CLI. 

The difference is one is created via text editor and another from VS code (not sure why sample2.txt did not work on your machine). But still, thanks for reminding about the new line issue!

**Comment by jeromesimeon** [comment]
@lilychau1 Some editors add new lines when saving to disk. As far as I can tell those two files are identical:
```
bash-3.2$ diff sample.txt sample2.txt 
bash-3.2$ diff sample.txt sample3.txt 
2c2
< Thank you!
---
> Thank you!
\ No newline at end of file
bash-3.2$
```

**Comment by jeromesimeon** [comment]
Closing this, feel free to re-open if related problems arise.
