### ISSUE TITLE
Typo in DEVELOPERS.md

### ISSUE THREAD

**Issue by shahsank3t** [accordproject/cicero#431]
**Describe the bug**
In DEVELOPERS.md ([here](https://github.com/accordproject/cicero/blob/master/DEVELOPERS.md#building-cicero)), URL of the main repository to be added as upstream has a typo in it. `acccordproject` should be `accordproject`

**To Reproduce**
1. Go to [DEVELOPERS.md](https://github.com/accordproject/cicero/blob/master/DEVELOPERS.md#building-cicero)
2. Check 'Add the main repository as an upstream remote to your repository'
3. Notice the typo in URL

**Expected behavior**
Instead of `acccordproject`, it should be `accordproject`

**Comment by shahsank3t** [comment]
@irmerk - can you please add some labels to this and assign it to me so I could quickly open a PR for this?

**Comment by jeromesimeon** [comment]
it's yours @shahsank3t !

**Comment by shahsank3t** [comment]
Thanks @jeromesimeon 
Opened PR: https://github.com/accordproject/cicero/pull/432
