### ISSUE TITLE
Build a List of Variable Names From Just a Cicero Template

### ISSUE THREAD

**Issue by JSv4** [accordproject/cicero#479]
Hi All,

Love the project and see a lot of promise in it. This is a feature request I'm submitting after a conversation I had on Accord with Matt and Jerome. There's no bug here, just a feature request.

Basically, I'm imagining a set of features to make creating a full Accord template from just the natural language Cicero templates easier. One of these would be a feature to parse just the Cicero template file and output a json with all of the variable names (and, if applicable, complex object variable names and properties). Next step might be to use those variable names to scaffold a half-finished model file.

Obviously you couldn't build a complete data model from this as you need to know the variable types in addition to the names. That said, I think this would be a helpful feature to help people build fully accord-compliant templates from just natural language contract templates written in Cicero Markdown. I find that's how a lot of people are used to making contract templates (starting with the contract text and then adding in variables and conditional blocks). Making it easier to author an entire natural language template and then pull out the various variable names that need to be wired up for logic and data types would save a lot of time IMHO and makes this a particularly useful feature.

Happy to help with this as it's a key feature for something I'm working on.

**Comment by jeromesimeon** [comment]
Just a few (not very organized) thoughts on this issue:

- For reference, the following issue includes some  discussion along the lines of "type annotations inside the grammar". https://github.com/accordproject/cicero/issues/162

- At the moment, there is very little that would work without at least a model for the grammar variables, so this will require a bit of design work and evaluating how this might change the user experience.

- It's quite possible that this kind of functionality could be done as a library on top of Concerto + Cicero.

- There is a meta-model for concerto here https://models.accordproject.org/concerto/metamodel.html
In theory one should be able to take a JSON object, instance of that meta-model, validate it and create a corresponding CTO model from it?

**Comment by mttrbrts** [comment]
Some other thoughts:
- Templates will parse successfully without any logic files. (Try this template after deleting `logic.ergo`, https://github.com/accordproject/cicero-template-library/tree/master/src/empty)

- The template loader throws an exception if there isn't a template model. https://github.com/accordproject/cicero/blob/68a9cdea0f1d3ef322e1bb244c84dda563c551bd/packages/cicero-core/src/template.js#L80

- The client application should take responsibility for producing a default empty model. Like the one in the `empty` template.

> a feature to parse just the Cicero template file and output a json with all of the variable names 

- We would require a new function in the Cicero API to do this. Perhaps called something like `template.inferModelProperties`?
```
// output of template.inferModelProperties()
 ["name", "contractValue" , ...  ]
```

- The client application would then be responsible for rebuilding the template model using the Concerto API and then recreating the template.

**Comment by JSv4** [comment]
@mttrbrts and @jeromesimeon , I've fleshed out an initial solution here and was hoping you might have some thoughts on the best way to proceed. 

Within parsermanager in the cicero-core, I created two methods:

1. **parseGrammarVariables( )** - a recursive method that takes the .data field of the nearley parser result and converts the various detected binding chunks into JSON objects of the form

`{
     variableName:"",
     variableType:"",
     fields:[]
} `

2. **inferVariablesFromTemplate( )** - as an entry point for parseGrammarVariables()

It seems like this approach will work base don the results I got (see below), but please let me know if you think there's an easier way to tie into the parser to get the variables. I'm still unravelling how the parser works. Also, I'm still a bit new to Javascript (though I've been programming in other languages for a long while), so please pardon any fugly syntax. 

With my two methods, passing in this example template:

```
{{#if forceMajeure}} This is an empty contract template to get you started. {{/if}} {{Boo}} '

{{#ulist rates}}
{{volumeAbove}}$ million <= Volume < {{volumeUpTo}}$ million : {{rate}}%
{{/ulist}}

{{#olist rates}}
{{volumeAbove}}$ million <= Volume < {{volumeUpTo}}$ million : {{rate}}%
{{/olist}}

{{#clause payment}}
As consideration in full for the rights granted herein, Licensee shall pay Licensor a one-time
fee in the amount of {{amountText}} ({{amount}}) upon execution of this Agreement, payable as
follows: {{paymentProcedure}}.
{{/clause}}

{{#with author}}
{{firstName}} {{lastName}}
{{/with}}
```

Yields this:
```
[
  {
    "variableName": "forceMajeure",
    "variableType": "boolean",
    "fields": []
  },
  {
    "variableName": "Boo",
    "variableType": "scalar",
    "fields": []
  },
  {
    "variableName": "rates",
    "variableType": "objectList",
    "fields": [
      {
        "variableName": "volumeAbove",
        "variableType": "scalar",
        "fields": []
      },
      {
        "variableName": "volumeUpTo",
        "variableType": "scalar",
        "fields": []
      },
      {
        "variableName": "rate",
        "variableType": "scalar",
        "fields": []
      }
    ]
  },
  {
    "variableName": "rates",
    "variableType": "objectList",
    "fields": [
      {
        "variableName": "volumeAbove",
        "variableType": "scalar",
        "fields": []
      },
      {
        "variableName": "volumeUpTo",
        "variableType": "scalar",
        "fields": []
      },
      {
        "variableName": "rate",
        "variableType": "scalar",
        "fields": []
      }
    ]
  },
  {
    "variableName": "author",
    "variableType": "object",
    "fields": [
      {
        "variableName": "firstName",
        "variableType": "scalar",
        "fields": []
      },
      {
        "variableName": "lastName",
        "variableType": "scalar",
        "fields": []
      }
    ]
  }
]
```

**This seems to work pretty well, but I have two issues.**

_The first is more substantive - how to extract a list of unique variable names from this structure while handling the possiblity of ambiguous or duplicate variable references_. For example, if there's a with block with a variable in it called "name", that's clearly going to be different than standalone variable named "name". Where things get a little fuzzy for me is with clauses. Should a variable called "name" in a clause be different than a variable called "name" in a different clause or outside the clause in the contract? Also, I feel like similar potential ambiguity arises with lists, but I need to think that through more to convince myself one way or another.

_The second issue I've run into is a few parser syntax issues that don't seem to be related to my proposed changes_. The following markdown examples right from the help docs and gave the following errors: 

1. This doesn't seem to parse at all and breaks the parser:

`{{#join rates ","}}
{{volumeUpTo}}
{{/join}}`

Specifically, I'm getting an error that:

>   {{#join
^
Unexpected startblockid token: "join"

2. This also doesn't seem to parse at all and breaks the parser:

```
{{#if isActive}}
  I'm active
{{else}}
  I'm not active
{{/if}}
```

Specific error is:

> invalid syntax at line 23 col 3:
> 
>   {{else
>     ^
> Unexpected varid token: "else"

3. Finally, referning to a field of an object in dot notation format doesn't return a parser output that looks anything like other variable bindings. The resulting JSON object has type "Expr" and has no variable name or other fields that I can find... Is that expected behavior? I'm referring to the .data field in the nearley parser output:

**My code so far**

```
inferVariablesFromTemplate(templatizedGrammar)
  {
      // Roundtrip the grammar through the Commonmark parser
      templatizedGrammar = this.roundtripMarkdown(templatizedGrammar); // console.log(templatizedGrammar);

      Logger.debug('buildGrammar', templatizedGrammar);
      const parser = new nearley.Parser(nearley.Grammar.fromCompiled(templateGrammar));
      parser.feed(templatizedGrammar);  
   
      if (parser.results.length !== 1) {
        throw new Error('Ambiguous parse!');
      } // parse the template grammar to generate a dynamic grammar
  
      const ast = parser.results[0];
  
      let parserOutput = ast.data;
  
      return this.parseGrammarVariables(parserOutput);
  }

  parseGrammarVariables(subElements){

    let fields = [];

    subElements.forEach((element) => {

      if(element.type === "Binding") {
        fields.push({
          variableName: element.fieldName.value,
          variableType: "scalar",
          fields: []
        });
      }
      else if (element.type==="BooleanBinding") {
        fields.push({
          variableName: element.fieldName.value,
          variableType: "boolean",
          fields: []
        });
      }
      else if (element.type==="FormattedBinding") {
        fields.push({
          variableName: element.fieldName.value,
          variableType: "formattedField",
          fields: []
        });
      }
      else if (element.type==="ListBinding") {
        fields.push({
          variableName: element.fieldName.value,
          variableType: "objectList",
          fields: this.parseGrammarVariables(element.template.data)
        });
      }
      else if (element.type==="WithBinding") {
        fields.push({
            variableName: element.fieldName.value,
            variableType:"object",
            fields: this.parseGrammarVariables(element.template.data)
          });
      }
      else {
        console.log("Unrecognized parser chunk type:");
        console.log(element);
      }
    });

    return fields;
  }
```

**Comment by dselman** [comment]
This is looking promising!

Here is some test code I wrote while thinking this through:

```
describe('ParserManager', () => {

    describe('#getTemplateAst', () => {

        it.only('should return the AST for a template', async () => {
            const packageJson = {
                name: 'my-template',
                version: '0.0.1',
                accordproject: {
                    template: 'clause',
                    cicero: '^0.20.0',
                    runtime: 'ergo'
                },
            };
            const template = new Template(packageJson, 'my readme', {default: 'This is a new template. Created by "Dan".'});
            const mm = template.getLogicManager().getModelManager();
            mm.addModelFile(`
namespace org.acme

import org.accordproject.cicero.contract.AccordClause from https://models.accordproject.org/cicero/contract.cto

asset MyClause extends AccordClause {
    o String author
}
`, 'mymodel.cto', true );

            await mm.updateExternalModels();

            const parserManager = new ParserManager(template);
            parserManager.buildGrammar( 'This is a new template. Created by {{author}}.' );
            const ast = parserManager.getTemplateAst();
            console.log(JSON.stringify(ast, null, 4));
        });
    });
});
```

This programatically creates a template in memory and attempts to parse the grammar to create the AST. If you remove the `o String author` from the model you will see that the template in now invalid, and grammar generation fails with the error:

```
TemplateException: Template references a property 'author' that is not declared in the template model 'org.acme.MyClause' File text/grammar.tem.md line 1 column 38
```

When the template is valid the test outputs:

```
{
    "type": "ContractTemplate",
    "data": [
        {
            "type": "Chunk",
            "value": "This is a new template. Created by ",
            "text": "This is a new template. Created by {{",
            "offset": 0,
            "lineBreaks": 0,
            "line": 1,
            "col": 1
        },
        {
            "type": "Binding",
            "fieldName": {
                "type": "varid",
                "value": "author",
                "text": "author",
                "offset": 37,
                "lineBreaks": 0,
                "line": 1,
                "col": 38
            }
        },
        {
            "type": "LastChunk",
            "value": ".",
            "text": ".",
            "offset": 45,
            "lineBreaks": 0,
            "line": 1,
            "col": 46
        }
    ]
}
```

So, I think the question may be mostly around UX - what should this guided template creation process look like? Using the code above you can imagine progressively "fixing" the template, where each fix would programmatically add a new property to the template model, prompting the user for type information as required.

Using your code you'd get a better global list of variables - but you'd still have to reconcile them with a template model, and supply the metadata for the template (package.json).

This sounds like a good discussion to continue in a Technology WG call if you are available (4 PM NYC time). It also relates to wip we are doing in Template Studio v2 ("Design Mode").

https://accordproject-studio.netlify.com

(Add a clause and then press the "Clause Navigation" link to view the artefacts for the Clause).

It would also be useful to reformulate this issue in terms of a User Story - so we are aligned on who is doing this work, why and what the next steps in their workflow might be.

**Comment by mttrbrts** [comment]
FYI @JSv4  I've opened a dedicated issue (#480) specifically for the parser problems.

**Comment by JSv4** [comment]
Thanks @mttrbrts . Wanted to make sure that wasn't just a me thing before reporting it.

I'd be happy to join the wg call, @dselman 
. Unfortunately, I'm tied up until 4:30 NYC time. I could join then if it's still going. The details usually circulate on Slack, right?

**Comment by dselman** [comment]
> I'd be happy to join the wg call, @dselman
> . Unfortunately, I'm tied up until 4:30 NYC time. I could join then if it's still going. The details usually circulate on Slack, right?

That works. Yes, the link to the Zoom meeting will be on Slack.

**Comment by dselman** [comment]
Thinking this through some more, here is an API approach that I think can work.
1. We add a new static method `Template.fromText(name, version, temFileText)`
2. This method creates a new Template, and creates a default readme, package.json based on name and version. It then calls a new method, below...
3. Add a new instance method on template `updateTemplateModelFromText(text)`
4. This method parses the text and adds any missing variables to the `ModelManager` for the template. It can assume `String` as the type (?).
5. Any variables that are in the `ModelManager` but not in the text are removed (option?)

**Comment by jeromesimeon** [comment]
> Thinking this through some more, here is an API approach that I think can work.
> 
> 1. We add a new static method `Template.fromText(name, version, temFileText)`
> 2. This method creates a new Template, and creates a default readme, package.json based on name and version. It creates an empty TemplateModel in the ModelManager. It then calls a new method, below...
> 3. Add a new instance method on template `updateTemplateModelFromText(text)`
> 4. This method parses the text and adds any missing variables to the `ModelManager` for the template. It can assume `String` as the type (?). If the variable has an `as` declaration then we assume that it is a `DateTime`.
> 5. Any variables that are in the `ModelManager` but not in the text are removed (option?)
> 
> > Note that we need to write code to serialise a `ModelManager` back to a CTO file, if we modify the `ModelManager` via API to add properties.

Couple more data points:
- The bigger case to distinguish is between `String` `Integer` and `Double`.
- `Boolean` variables can be inferred from `{{#if}}...{{/if}}` blocks
- `parse` and `draft` will likely not work if any of the inferred types are not correct. What will the user test with?

**Comment by dselman** [comment]
Once we have a Nearly grammar we can use it to generate a sample using the Nearly API.

**Comment by dselman** [comment]
I am working on a new Concerto feature to save the `ModelManager` as a set of CTO files to support this:
https://github.com/accordproject/concerto/issues/153

**Comment by jeromesimeon** [comment]
Hi @JSv4,

> @mttrbrts and @jeromesimeon , I've fleshed out an initial solution here and was hoping you might have some thoughts on the best way to proceed.
> 
...
> 
> 1. This doesn't seem to parse at all and breaks the parser:
> 
> `{{#join rates ","}} {{volumeUpTo}} {{/join}}`
> 
> Specifically, I'm getting an error that:
> 
> > {{#join
> > ^
> > Unexpected startblockid token: "join"
> 
> 1. This also doesn't seem to parse at all and breaks the parser:
> 
> ```
> {{#if isActive}}
>   I'm active
> {{else}}
>   I'm not active
> {{/if}}
> ```
> 
> Specific error is:
> 
> > invalid syntax at line 23 col 3:
> > {{else
> > ^
> > Unexpected varid token: "else"
>

I have a fix in for those parser bugs. I'll do a `0.20.1` release (most likely tomorrow). But in the meantime, if you would like to test is, it is available in `@accordproject/cicero-core@0.20.1-20191107191813`

I had to refactor/cleanup the parser code a bit, and this will affect your code since you rely on AST node information. Most specifically, in your code below:

`BooleanBinding` has become `IfBinding`
`ListBinding` comes now in three flavors: `UListBinding` `OListBinding` and `JoinBingins`.

Let me know if any questions or issues!

> 1. Finally, referning to a field of an object in dot notation format doesn't return a parser output that looks anything like other variable bindings. The resulting JSON object has type "Expr" and has no variable name or other fields that I can find... Is that expected behavior? I'm referring to the .data field in the nearley parser output:
> 
> **My code so far**
> 
> ```
> inferVariablesFromTemplate(templatizedGrammar)
>   {
>       // Roundtrip the grammar through the Commonmark parser
>       templatizedGrammar = this.roundtripMarkdown(templatizedGrammar); // console.log(templatizedGrammar);
> 
>       Logger.debug('buildGrammar', templatizedGrammar);
>       const parser = new nearley.Parser(nearley.Grammar.fromCompiled(templateGrammar));
>       parser.feed(templatizedGrammar);  
>    
>       if (parser.results.length !== 1) {
>         throw new Error('Ambiguous parse!');
>       } // parse the template grammar to generate a dynamic grammar
>   
>       const ast = parser.results[0];
>   
>       let parserOutput = ast.data;
>   
>       return this.parseGrammarVariables(parserOutput);
>   }
> 
>   parseGrammarVariables(subElements){
> 
>     let fields = [];
> 
>     subElements.forEach((element) => {
> 
>       if(element.type === "Binding") {
>         fields.push({
>           variableName: element.fieldName.value,
>           variableType: "scalar",
>           fields: []
>         });
>       }
>       else if (element.type==="BooleanBinding") {
>         fields.push({
>           variableName: element.fieldName.value,
>           variableType: "boolean",
>           fields: []
>         });
>       }
>       else if (element.type==="FormattedBinding") {
>         fields.push({
>           variableName: element.fieldName.value,
>           variableType: "formattedField",
>           fields: []
>         });
>       }
>       else if (element.type==="ListBinding") {
>         fields.push({
>           variableName: element.fieldName.value,
>           variableType: "objectList",
>           fields: this.parseGrammarVariables(element.template.data)
>         });
>       }
>       else if (element.type==="WithBinding") {
>         fields.push({
>             variableName: element.fieldName.value,
>             variableType:"object",
>             fields: this.parseGrammarVariables(element.template.data)
>           });
>       }
>       else {
>         console.log("Unrecognized parser chunk type:");
>         console.log(element);
>       }
>     });
> 
>     return fields;
>   }
> ```

**Comment by JSv4** [comment]
Thanks, @jeromesimeon. Will give it a shot tonight and try to pick this up. @dselman, I will explore your suggested Template.fromText() approach and keep in mind the work you're doing on Issue 153.

**Comment by jeromesimeon** [comment]
> Thanks, @jeromesimeon. The ifelse and join blocks are working now!
> 

Great @JSv4 Thanks for confirming! This fix is now officially in Cicero `0.20.1`.

**Comment by JSv4** [comment]
@jeromesimeon awesome! Saw the announcement. Making good progress on being able to create a model file. Going to do some more tweaking this weekend.

**Comment by JSv4** [comment]
@jeromesimeon , made a lot of progress on this. I am able to generate model files for fairly complex templates that look right to me. The code is a bit of a mess of recursive methods that is inefficient and needs cleanup, but I'm optimistic I am close to a reasonably robust solution that I can optomize next. I keep running into an apparet syntax error when trying to use the generated models, however, and I'm getting the same thing when I write them out myself, leading me to believe I'm screwing up something simple but fundemantal with the model file syntax? I assume this is due to something I'm doing that's stupid, but I'm pulling my hair out trying to figure out what I keep getting the error:

> ERROR! Template references a property 'rates' that is not declared in the template model 'org.accordproject.empty.EmptyContract' File text/grammar.tem.md line 1 column 10

With the following example model:

```
namespace org.accordproject.empty

import org.accordproject.cicero.contract.* from https://models.accordproject.org/cicero/contract.cto
import org.accordproject.cicero.runtime.* from https://models.accordproject.org/cicero/runtime.cto

// Template model
asset EmptyContract extends AccordContract {
  o rates_list_obj[] rates
}

concept rates_list_obj {
  o String volumeAbove
  o String volumeUpTo
  o String rate
}
// Request
transaction EmptyRequest extends Request {
}

// Response
transaction EmptyResponse extends Response {
}
```

And the following example template:

```
{{#ulist rates}}
{{volumeAbove}}$ million <= Volume < {{volumeUpTo}}$ million : {{rate}}%
{{/ulist}}
```

Any thoughts?

**Comment by dselman** [comment]
Please create a new issue on Cicero for that and attach the zip of the cta file so we can debug. Thanks!

**Comment by JSv4** [comment]
@dselman and @jeromesimeon , good news! Got this working. I can generate a model, logic file and sample data for a fairly complex template and everything seems to be working nicely. If you guys have a  second, I was hoping you could answer a few questions about Cicero Mark so I could make sure I'm testing the full gamut of template variable reference. 

Specifically:

1. Do lists have to refer to concepts? Could I have a lost of primitives?
2. Which types of primitives can be formatted, and where would I find the universe of supported formats?

I'm going to do a little cleanup on the code and make sure I've tested more corner cases in the templates. Once I've done that, should I go ahead and make a pull request?

**Comment by jeromesimeon** [comment]
> @dselman and @jeromesimeon , good news! Got this working. I can generate a model, logic file and sample data for a fairly complex template and everything seems to be working nicely. If you guys have a second, I was hoping you could answer a few questions about Cicero Mark so I could make sure I'm testing the full gamut of template variable reference.

That's great news! I'll be excited to see it in action!

> 
> Specifically:
> 
> 1. Do lists have to refer to concepts? Could I have a lost of primitives?

At the moment yes. You have to wrap every level in concepts. This limitation could be lifted if we added a new special variable like `this` for the current item in a list for instance.

> 2. Which types of primitives can be formatted, and where would I find the universe of supported formats?
> 

Currently only date/time. See https://docs.accordproject.org/docs/markup-variables.html#primitive-types-with-a-format

> I'm going to do a little cleanup on the code and make sure I've tested more corner cases in the templates. Once I've done that, should I go ahead and make a pull request?

Sure! We can review the details better on a PR. I'm notably interested to see how that fits with the current Cicero API.

**Comment by JSv4** [comment]
@jeromesimeon, you can ignore my earlier comments :-). It was, unsurprisingly, something I was doing wrong. 

I'm am almost done testing this. It's working nicely and I can generate entire CTO packages from a single templatized grammar. 

I am running into a slighlty odd thing that I think is an error with template studio. I was going to submit an issue but looks like you guys are well on your way to getting studio v2 ready and it's probably not worth it. That said, wanted to see if this behavior is expected?

I've created a very simple cto automatically from this, and it works great:
```
#### Discount.

The Discount is determined according to the following table:

Unordered List:
{{#ulist rates}}{{volumeAbove}}$ million <= Volume < {{volumeUpTo}}$ million : {{rate}}%{{/ulist}}

Ordered List:
{{#olist rates}}{{volumeAbove}}$ million <= Volume < {{volumeUpTo}}$ million : {{rate}}%{{/olist}}
```

If I add a newline after the list tag and before the closing tag, however, I get the error:
> [Instantiate Contract] Cannot read property '$class' of null

This is the template causing the error:
```
#### Discount.

The Discount is determined according to the following table:

Unordered List:
{{#ulist rates}}{{volumeAbove}}$ million <= Volume < {{volumeUpTo}}$ million : {{rate}}%{{/ulist}}

Ordered List:
{{#olist rates}}
{{volumeAbove}}$ million <= Volume < {{volumeUpTo}}$ million : {{rate}}%
{{/olist}}
```
I think the error is in Template Studio, however, and not the parser (or my template grammar) because I can validate this templatizedGrammar in my own code using template.validate(). I can also use Util.draft successfully to create a sample from the templatizedGrammar.

Let me know if I'm offbase here and the newlines I've put after the list tags aren't supported.

**Comment by dselman** [comment]
@jeromesimeon tagging you on this, because it sounds like your recent work on TemplateMark should make this much easier.

**Comment by jeromesimeon** [comment]
This should now be drastically simplified by switching to the new parser. The new markdown transform generate a proper JSON Document Object Model for the template grammar called TemplateMark. Here it is on a simple example:

```
bash-3.2$ cd ~/git/cicero-template-library/src/full-payment-upon-demand
bash-3.2$ ~/git/markdown-transform/packages/markdown-cli/index.js transform --from grammar --to templatemark --ctoFiles model/model.cto --input text/grammar.tem.md --contract 
~/git/markdown-transform/packages/markdown-cli/index.js transform --from grammar --to templatemark --ctoFiles model/model.cto --input text/grammar.tem.md --contract 
9:13:54 PM - info:
{
  "$class": "org.accordproject.commonmark.Document",
  "xmlns": "http://commonmark.org/xml/1.0",
  "nodes": [
    {
      "$class": "org.accordproject.templatemark.ContractDefinition",
      "name": "top",
      "elementType": "org.accordproject.payment.fullupondemand.FullPaymentUponDemandTemplate",
      "nodes": [
        {
          "$class": "org.accordproject.commonmark.Paragraph",
          "nodes": [
            {
              "$class": "org.accordproject.commonmark.Text",
              "text": "After execution of this Agreement, "
            }, 
            {
              "$class": "org.accordproject.templatemark.VariableDefinition",
              "name": "buyer",
              "elementType": "org.accordproject.cicero.contract.AccordParty"
            }, 
            {
              "$class": "org.accordproject.commonmark.Text",
              "text": " shall pay the full purchase price to "
            }, 
            {
              "$class": "org.accordproject.templatemark.VariableDefinition",
              "name": "seller",
              "elementType": "org.accordproject.cicero.contract.AccordParty"
            }, 
            {
              "$class": "org.accordproject.commonmark.Text",
              "text": " in the amount of "
            }, 
            {
              "$class": "org.accordproject.templatemark.VariableDefinition",
              "name": "value",
              "elementType": "org.accordproject.money.MonetaryAmount"
            }, 
            {
              "$class": "org.accordproject.commonmark.Text",
              "text": " upon demand by "
            }, 
            {
              "$class": "org.accordproject.templatemark.VariableDefinition",
              "name": "seller",
              "elementType": "org.accordproject.cicero.contract.AccordParty"
            }, 
            {
              "$class": "org.accordproject.commonmark.Text",
              "text": "."
            }
          ]
        }
      ]
    }
  ]
}
bash-3.2$ 
```

It shouldn't be hard to write a simple visitor on that JSON to extract the `VariableDefinition` nodes (along with `FormattedVariableDefinition` and `EnumVariableDefinition` which are indicated separately). This currently contains type information, but it could be exposed untyped (without passing a model) if need be.

@JSv4 let me know if you think this can help or if any feedback about this.

**Comment by JSv4** [comment]
@jeromesimeon, sorry, I've been totally wrapped up in another project. Hoping to have it in a good spot in the next week or two and then I'll hopefully have time to take another crack at this. Loving all of the new features you guys have built!

**Comment by jeromesimeon** [comment]
@JSv4 no problem! Cicero version `0.21` and the underlying markdown library `markdown-transform` version `0.21` are both now out the door, so you should be able to give it a try.

To get the document object model in JSON for the template (aka the template mark Dom):

```
bash-3.2$ npm install -g @accordproject/markdown-cli 
/Users/jeromesimeon/.nvm/versions/node/v10.17.0/bin/markus -> /Users/jeromesimeon/.nvm/versions/node/v10.17.0/lib/node_modules/@accordproject/markdown-cli/index.js
+ @accordproject/markdown-cli@0.12.0
updated 1 package in 34.748s
bash-3.2$ markus --version
0.12.0
bash-3.2$ markus transform --from markdown_template --to templatemark --model ~/git/cicero-template-library/src/acceptance-of-delivery/model/model.cto --input ~/git/cicero-template-library/src/acceptance-of-delivery/text/grammar.tem.md 
<template-library/src/acceptance-of-delivery/text/grammar.tem.md 
9:51:01 PM - info:
{
  "$class": "org.accordproject.commonmark.Document",
  "xmlns": "http://commonmark.org/xml/1.0",
  "nodes": [
    {
      "$class": "org.accordproject.templatemark.ClauseDefinition",
      "name": "top",
      "elementType": "org.accordproject.acceptanceofdelivery.AcceptanceOfDeliveryClause",
      "nodes": [
        {
          "$class": "org.accordproject.commonmark.Heading",
          "level": "2",
          "nodes": [
            {
              "$class": "org.accordproject.commonmark.Text",
              "text": "Acceptance of Delivery."
            }
          ]
        }, 
        {
          "$class": "org.accordproject.commonmark.Paragraph",
          "nodes": [
            {
              "$class": "org.accordproject.templatemark.VariableDefinition",
              "identifiedBy": "identifier",
              "name": "shipper",
              "elementType": "org.accordproject.organization.Organization"
            }, 
...
```

**Comment by jeromesimeon** [comment]
You can find a very simple visitor that would do the trick in this Gist: https://gist.github.com/jeromesimeon/242ae53b0586534954f40664cb21b5a0

To run:
```
bash-3.2$ node run.js 
["shipper","receiver","deliverable","receiver","shipper","deliverable","receiver","businessDays","deliverable","shipper","deliverable","deliverable","shipper","attachment"]
```

**Comment by jeromesimeon** [comment]
> You can find a very simple visitor that would do the trick in this Gist: https://gist.github.com/jeromesimeon/242ae53b0586534954f40664cb21b5a0
> 
> To run:
> 
> ```
> bash-3.2$ node run.js 
> ["shipper","receiver","deliverable","receiver","shipper","deliverable","receiver","businessDays","deliverable","shipper","deliverable","deliverable","shipper","attachment"]
> ```

I think this addresses the original issue. Closing this. Feel free to reopen (or open a new issue) if more questions.
