### ISSUE TITLE
Add Accord Project Tag to Cicero generator

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/cicero#487]
The Cicero template generator creates a `README.md` for generated templates. Once we have an approved/agreed upon "Powered by Accord Project" badge, it would be nice if the Cicero generator automatically includes it in the `README.md`

See: https://github.com/accordproject/techdocs/issues/81

**Comment by shashikant231** [comment]
hello.can i take up this issue?
thanks!!

**Comment by jeromesimeon** [comment]
> hello.can i take up this issue?
> thanks!!

This issue only makes sense after https://github.com/accordproject/techdocs/issues/81 has been resolved.

**Comment by jeromesimeon** [comment]
Fixed in #535
