### ISSUE TITLE
"Error in if (sum (dist_mat> distance_constraint) / 2 <1)" is reported when running Cicero

### ISSUE THREAD

**Issue by lidenghui92** [accordproject/cicero#503]
hello,
       I am currently running an R script with Cicero loaded, but I get an error when running Cicero, as follows：
###############################
[1] "Starting Cicero"
[1] "Calculating distance_parameter value"
Error in if (sum(dist_mat > distance_constraint)/2 < 1) { :
  missing value where TRUE/FALSE needed
Calls: doCicero_gascore ... estimate_distance_parameter -> find_distance_parameter
In addition: Warning messages:
1: In order(as.character(dhsinfo$chr), as.numeric(as.character(dhsinfo$bp2))) :
  NAs introduced by coercion
2: In make_atac_cds(dt, binarize = T) : NAs introduced by coercion
3: In make_atac_cds(dt, binarize = T) : NAs introduced by coercion
Execution halted
##############################
Will you help me with this problem? thank you very much.

David

**Comment by jeromesimeon** [comment]
@lidenghui92 I'm wondering if you have the correct project. Do you mean: https://cole-trapnell-lab.github.io/cicero-release/docs/ ?

**Comment by lidenghui92** [comment]
thank you  a lot. I just test the scATAC-pro pipeline:(https://github.com/wbaopaul/scATAC-pro) .The problem described above happend, we try to solve it,but we have no way,so we need your help a lot,thanks for your response.

**Comment by jeromesimeon** [comment]
I don't know either of those, this GitHub repository is for the Cicero package which is part of the accord project (https://docs.accordproject.org). If you're using R you are most likely using this other library with the same name in the link above.

**Comment by lidenghui92** [comment]
ok, Thank you for your suggestion, thank you again.
