### ISSUE TITLE
Embedding Ergo Scripts / Ergo inside CiceroMark conditional template variables

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/cicero#519]
From @martinhalford 

## Embedding Ergo Scripts:

At the moment, Ergo scripts within contracts are standalone.  It's not possible to embed variables within scripts that expect strings only. 

For example, it's valid to have: 

`{{#if sellerPrice}} It's true! {{else}} Nope, it's not true.{{/if}}`

but you can't have...

```
{{#if sellerPriceRange}} The seller's price is between ${{priceLow}} 
and ${{priceHigh}} {{else}} The seller's price is: ${{price}} {{/if}}
```

or embedded expressions...

```
{#if sellerPriceRange} The value is: {{#with property}}${{price}}{{/with}}
{{else}} The value is between {{#with property}}${{priceLow}} and 
{{#with property}}${{priceHigh}}{{/with}}{{/if}}
```
This would significantly improve the sophistication possible for contract templates that are used at volume for many contract instances with different but similar criteria.

**Comment by jeromesimeon** [comment]
This feature can be now supported for optional types, using the new optional block in AP templates in Cicero `0.21`. An example can be found in the template library: https://templates.accordproject.org/latedeliveryandpenalty-optional@0.1.0.html

@martinhalford Let me know if we can close this issue.

**Comment by martinhalford** [comment]
LGTM 👍 Feel free to close. Thank you!!
