### ISSUE TITLE
`template.hasLogic()` returning `true` even if template has no logic

### ISSUE THREAD

**Issue by algomaster99** [accordproject/cicero#529]
**Describe the bug**
`template.hasLogic()` returning `true` even if a template has no logic.

**To Reproduce**
1. Create a template without a logo in it.
2. `console.log` its `template.hasLogic()`
3. The output is `true`

**Expected behavior**
Since the template has no logo, it should return `false`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS

**Additional context**
`template.hasLogic()` returns `template.getScriptManager().getAllScripts().length > 0`. And the array returned by `template.getScriptManager()[0].getContents()` is the compilation for the template grammar.

**Comment by jeromesimeon** [comment]
This is an (unnoticed) artefact of the `0.20` in which the template grammar gets compiled to JavaScript using the Ergo compiler to support the new `TemplateInstance.draft` API call.

This should be changed to properly return `false` for templates without _execution_ logic.

Note: I don't think this call is used anywhere at the moment, but could be important to support "design model" in Cicero UI.

**Comment by jeromesimeon** [comment]
This is fixed in #559
