### ISSUE TITLE
Changes in timezone are not handled in parsing dates

### ISSUE THREAD

**Issue by algomaster99** [accordproject/cicero#531]
**Describe the bug**
`dateTimeProperty` is not being parsed correctly and in accordance with timezone changes.

**To Reproduce**
1. Run the full test suite of `cicero`

**Expected behavior**
The following tests should have passed
```
1) FormattedDates
       #draft - formatted-dates-DD_MM_YYYY
         should be able to roundtrip formatted-dates natural language text:

      AssertionError: expected 'dateTimeProperty: 30/11/2018' to equal 'dateTimeProperty: 01/12/2018'
      + expected - actual

      -dateTimeProperty: 30/11/2018
      +dateTimeProperty: 01/12/2018
      
      at Context.<anonymous> (test/formattedDates.js:68:27)

  2) FormattedDates
       #draft - formatted-dates-MM_DD_YYYY
         should be able to roundtrip formatted-dates natural language text:

      AssertionError: expected 'dateTimeProperty: 12/30/2019' to equal 'dateTimeProperty: 12/31/2019'
      + expected - actual

      -dateTimeProperty: 12/30/2019
      +dateTimeProperty: 12/31/2019
      
      at Context.<anonymous> (test/formattedDates.js:68:27)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional Context**
https://github.com/accordproject/cicero/pull/525#issuecomment-605024212

**Comment by algomaster99** [comment]
```
runVMScriptCall(utcOffset,now,options,context,script,call) {
        const vm = new VM({
            timeout: 1000,
            sandbox: {
                moment: moment,
                logger: Logger,
                utcOffset: utcOffset,
                now: now,
                options: options
            }
        });
        vm.freeze(context, 'context');
        vm.run(script);
        return vm.run(call);
    }
```
I think this part of the code isn't able to handle timezone changes. It is not converting the time parsed correctly.

**Comment by algomaster99** [comment]
@jeromesimeon Please look into this if you have time. :sweat_smile:

**Comment by jeromesimeon** [comment]
> @jeromesimeon Please look into this if you have time. 😅

I have a lot on my list for the coming release, but it's on my radar. Please bear with me.

**Comment by algomaster99** [comment]
@jeromesimeon Sure! :)

**Comment by Cronus1007** [comment]
@algomaster99 Shall I work upon this issue.

**Comment by Cronus1007** [comment]
@algomaster99 This issue doen't exist any more. So it is safe to close this issue.

**Comment by algomaster99** [comment]
@Cronus1007 thanks! I think https://github.com/accordproject/cicero/issues/547 takes care of it.
