### ISSUE TITLE
#getTemplateIndex of TemplateLibrary test suite failing

### ISSUE THREAD

**Issue by algomaster99** [accordproject/cicero#532]
**Describe the bug**
#getTemplateIndex of TemplateLibrary test suite failing

**To Reproduce**
1. Run the full test suite of `cicero`.

**Expected behavior**
The following test should have passed:
```
3) TemplateLibrary
       #getTemplateIndex
         should fail to retrieve index:

      AssertionError: expected promise to be rejected with an error including 'Error: getaddrinfo ENOTFOUND foo.bar foo.bar:80' but got 'Error: getaddrinfo ENOTFOUND foo.bar'
      + expected - actual

      -Error: getaddrinfo ENOTFOUND foo.bar
      +Error: getaddrinfo ENOTFOUND foo.bar foo.bar:80
      
      at /home/poski/Desktop/accord/cicero/node_modules/chai-as-promised/lib/chai-as-promised.js:215:30
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
https://github.com/accordproject/cicero/pull/525#issuecomment-605024212

**Comment by jeromesimeon** [comment]
To clarify: it looks like it is failing as expected but with a different message, is that correct?

**Comment by algomaster99** [comment]
@jeromesimeon yes, you are corr

**Comment by jeromesimeon** [comment]
@algomaster99 I think this should now be fixed in master through #534 Would you be able to check on your setup?

**Comment by algomaster99** [comment]
@jeromesimeon Yes! This test passes now :) Can you please summarize what was going wrong?

**Comment by jeromesimeon** [comment]
> @jeromesimeon Yes! This test passes now :) Can you please summarize what was going wrong?

The error is an internal http error, simply the behaviour for this is slightly different on your Linux machine and on MacOS (and possibly on Windows also). I've just made the test a little more permissive so it doesn't break on those variations.

Feel free to close since it's working 😉
