### ISSUE TITLE
Get latest version of templates compatible with specified cicero version

### ISSUE THREAD

**Issue by DianaLease** [accordproject/cicero#545]
**Is your feature request related to a problem? Please describe.**
Currently, a user can call `templateLibrary.getTemplateIndex()` with the option `latestVersion: true` to get the latest version of each template or passing a `ciceroVersion` to specify getting all the templates compatible with a specified version. However, there is no way to get the latest version of each template that is compatible with the specified cicero version. If you pass both, right now you will only receive templates that match that cicero version IFF the version that matches the cicero version is also the latest version of that template.

**Describe the solution you'd like**
If both options are passed (`latestVersion` and `ciceroVersion`), I think this call should return the latest version of each template compatible with that cicero version. (ie. "get me only the latest version of each template for this specified cicero version")

**Comment by Catherinesjkim** [comment]
I second that.

**Comment by jeromesimeon** [comment]
@DianaLease This should now be fixed, as suggested in Cicero `0.21.2` https://github.com/accordproject/cicero/releases/tag/v0.21.2

Let me know if this works and if we can close.

**Comment by jeromesimeon** [comment]
Closing this. Feel free to reopen if needed.
