### ISSUE TITLE
Unable to parse template containing unordered list markdown

### ISSUE THREAD

**Issue by martinhalford** [accordproject/cicero#560]
**Describe the bug**
Using the following snippet of template grammar....

`{{#ulist vendors}} Name: {{fullName}}, Email: {{email}}, Mobile: {{mobile}}{{/ulist}} .....etc.`

...the Cicero CLI `draft` command generates markdown that looks like this....

`-  Name: "Jack Walnut", Email: "jackwalnut@gmail.com", Mobile: "0432 123456" .....etc.`
`-  Name: "Betty Beetroot", Email: "bettybeetroot@gmail.com", Mobile: "0422 4545454" .....etc.`

However, the Cicero CLI `parse` cannot handle the reverse and throws the following error when attempted to parse the markdown....

`12:16:20 PM - error: invalid syntax at line 41 col 1:`
`  -  Name: "Jack Walnut", Email: "jackwalnut@gmail.com", Mobile: "0432 123456" .....etc.`
`  ^`
`Unexpected "-"`

**To Reproduce**
1. Insert sample grammar into grammar.tem.md `{{#ulist vendors}} Name: {{fullName}}, Email: {{email}}, Mobile: {{mobile}}{{/ulist}}`
2. Execute `cicero draft` using template containing grammar, and output new `sample.md` file.
3. Execute `cicero parse` on same template using `sample.md`.

**Expected behavior**
Ideally, expect `parse` to generate `data.json` from parsed unordered list in markdown.
Minimally, expect `parse` to gracefully handle error generated by unordered list in markdown. 

**Cicero CLI**
 - Version 0.20.10

**Comment by martinhalford** [comment]
@jeromesimeon - I assume this is just a straight bug that might be fixed in version 0.21 - correct?

**Comment by martinhalford** [comment]
Hi @jeromesimeon - I've retested this in Cicero 0.21 and the issue still seems to be present.  Here are the steps to reproduce using the `listquote` template archive.

[listquote.zip](https://github.com/accordproject/cicero/files/5013602/listquote.zip)

```
~/Desktop $ cicero --version
0.21.0
~/Desktop $ cicero draft --template ./listquote --data ./listquote/data.json --output ./listquote/text/sample.md
12:39:01 PM - info: Creating file: ./listquote/text/sample.md
12:39:01 PM - info: This is a contract
-  Name: "Jack Walnut"
   Email: "jackwalnut@gmail.com"
   Mobile: "0432 123456"
   Phone:  "(03) 887 7766"
   ABN:  "Not applicable"
   ACN: "Not applicable"
-  Name: "Betty Beetroot"
   Email: "bettybeetroot@gmail.com"
   Mobile: "0422 4545454"
   Phone:  "(03) 996 6677"
   ABN:  "Not applicable"
   ACN: "Not applicable"

This is more text
~/Desktop $ cicero parse --template ./listquote --sample ./listquote/text/sample.md
12:39:14 PM - error: Parse error at line 3 column 1
   Email: "jackwalnut@gmail.com"
^^^^^^^
Expected: 'Email: '
ParseException: Parse error at line 3 column 1
   Email: "jackwalnut@gmail.com"
^^^^^^^
Expected: 'Email: '
    at _throwParseError (/Users/martin/.nvm/versions/node/v10.16.3/lib/node_modules/@accordproject/cicero-cli/node_modules/@accordproject/markdown-template/lib/TemplateMarkTransformer.js:88:11)
```

Stuff I tried....
1. Tried removing excess whitespace in generated `sample.md` file (in front of "Email", "Mobile" etc.) to match `grammar.tem.md`.
2. Tried stringifying `sample.md` file. See (1) below.
3. Tried removing excess whitespace and stringifying `sample.md` file. See (2) below.
...but still throws error.

(1)
```
"This is a contract\n-  Name: \"Jack Walnut\"\n   Email: \"jackwalnut@gmail.com\"\n   Mobile: \"0432 123456\"\n   Phone:  \"(03) 887 7766\"\n   ABN:  \"Not applicable\"\n   ACN: \"Not applicable\"\n-  Name: \"Betty Beetroot\"\n   Email: \"bettybeetroot@gmail.com\"\n   Mobile: \"0422 4545454\"\n   Phone:  \"(03) 996 6677\"\n   ABN:  \"Not applicable\"\n   ACN: \"Not applicable\"\n\nThis is more text"
```

(2)
```
"This is a contract\n-  Name: \"Jack Walnut\"\nEmail: \"jackwalnut@gmail.com\"\nMobile: \"0432 123456\"\nPhone:  \"(03) 887 7766\"\nABN:  \"Not applicable\"\nACN: \"Not applicable\"\n-  Name: \"Betty Beetroot\"\nEmail: \"bettybeetroot@gmail.com\"\nMobile: \"0422 4545454\"\nPhone:  \"(03) 996 6677\"\nABN:  \"Not applicable\"\nACN: \"Not applicable\"\n\nThis is more text"
```

**Comment by jeromesimeon** [comment]
@martinhalford My bad for looking at this issue too quickly. The syntax for list blocks is:
```
{{#ulist vendors}}
Name: {{fullName}}, Email: {{email}}, Mobile: {{mobile}}
{{/ulist}}
```

Rather than

```
{{#ulist vendors}} Name: {{fullName}}, Email: {{email}}, Mobile: {{mobile}}{{/ulist}}
```

(the distinction is between markdown blocks such as paragraphs, lists, and headings and markdown inlines such as text, emphasis, etc)

Would you be able to try your example again with that change in the grammar?

**Comment by martinhalford** [comment]
Hi @jeromesimeon - Good news!  The bug is no more.  

For the record, the syntax of the list block in the `grammar.tem.md` was correct, as per below and in `listquote.zip`.
```
This is a contract

{{#ulist vendors}}
Name: {{fullName}}
Email: {{email}}
Mobile: {{mobile}}
Phone:  {{phone}}
ABN:  {{ABN}}
ACN: {{ACN}}
{{/ulist}}

This is more text
```
When reproducing the steps in `v0.21.0` is `parse` command failed but now in `v0.21.5` the `parse` command works! :-) 
Thank you!
