### ISSUE TITLE
Cicero Server README out of date.

### ISSUE THREAD

**Issue by martinhalford** [accordproject/cicero#563]
**Describe the bug**
The Cicero Server README is out of sync with recent changes to codebase.

**Comment by jeromesimeon** [comment]
PRs welcome!

**Comment by martinhalford** [comment]
LOL. I raised this issue so I can submit my PR! :-)

**Comment by jeromesimeon** [comment]
@martinhalford Can we close this?

**Comment by martinhalford** [comment]
LGTM 👍
