### ISSUE TITLE
Cicero draft should allow markdown_cicero as format (used as default)

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/cicero#574]
The API for draft would be nicer if it allowed `markdown_cicero` as a format, as all other formats. This is currently the default behaviour when there is no options, but the call will fail if the format is `markdown_cicero` at the moment.

**Comment by DianaLease** [comment]
clause.draft({ format: 'markdown_cicero' }) should return the text as `markdown_cicero` instead of throwing the error `Unsupported format: markdown_cicero`
