### ISSUE TITLE
Function "format" not available within Ergo Expression

### ISSUE THREAD

**Issue by martinhalford** [accordproject/cicero#599]
Consider the following grammar:
```
{{%
    if toString(dueDate) != ""
    then "Payment due on: " ++ format(dueDate, "DD MMMM YYYY")
    else ""
%}}
```
where dueDate is defined in the model as:
```
o DateTime dueDate
```
The output is:
```
error: Compilation error (at file formula_ad595e03bc3978e0b6cbb40f42a131a18c562648d8894b4baad7b7f4377bfa51 line 3 col 31). Cannot find function with name 'format'
    then "Payment due on: " ++ format(dueDate, "DD MMMM YYYY")
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Other functions, such as `toString` work fine.

Would be nice if we could format DateTime variables within Ergo Expression blocks.

Also.... note that, even though it is not needed, the Ergo syntax *must* have an `else` clause, otherwise the compiler throws a parser error.

For examples, this syntax fails...
```
{{%
    if toString(dueDate) != ""
    then "Payment due on: " ++ toString(dueDate)
%}}
```
whereas, this syntax is fine...
```
{{%
    if toString(dueDate) != ""
    then "Payment due on: " ++ toString(dueDate)
    else ""
%}}
```
Would be nice if `else` clause was optional.

To reproduce, execute draft command on attached template using the included data.json file:
```
cicero draft --template . --data ./data.json --output ./text/sample.md --unquoteVariables
```

[empty-contract.zip](https://github.com/accordproject/markdown-transform/files/5426643/empty-contract.zip)

**Comment by jeromesimeon** [comment]
I'll have to dig out the status of that `format` function. My hunch is that it's been removed, but left in the documentation.

However, you can use date time formatting in Ergo using the `Expr as Format` expression:

```
bash-3.2$ more text/grammar.tem.md 
Name: {{name}} 
Payment due by {{dueDate as "DD MMMM YYYY"}}

{{%
    if toString(dueDate) != ""
    then "Payment due on: " ++ dueDate as "DD MMMM YYYY"
    else ""
%}}
bash-3.2$ cicero draft --template . --data ./data.json --output ./sample.md --unquoteVariables
8:37:44 AM - info: Creating file: ./sample.md
8:37:44 AM - info: Name: Fred
Payment due by 17 December 2020

Payment due on: 17 December 2020
```

**Comment by jeromesimeon** [comment]
About the separate question:

> Also.... note that, even though it is not needed, the Ergo syntax _must_ have an `else` clause, otherwise the compiler throws a parser error.
> 

What would you want the expression to return if the condition is false?

I might be wrong, but I am guessing that answer is likely dependent on the context (here maybe `""` but maybe something different for other conditionals).

**Comment by jeromesimeon** [comment]
Actually, the `format` function does work as expected, but it's in the `org.accordproject.time` library: https://docs.accordproject.org/docs/ref-ergo-stdlib.html#time

So you will need to import it (as you would for any other date time functions):

```
bash-3.2$ cat logic/logic.ergo
namespace org.accordproject.empty

// Import time functions
import org.accordproject.time.*

contract Empty over EmptyContract {
  clause donothing(request : EmptyRequest) : EmptyResponse {
    return EmptyResponse{}
  }
}
bash-3.2$ more text/grammar.tem.md
Name: {{name}} 
Payment due by {{dueDate as "DD MMMM YYYY"}}

{{%
    if toString(dueDate) != ""
    then "Payment due on: " ++ format(dueDate,"DD MMMM YYYY")
    else ""
%}}
bash-3.2$ cicero draft --template . --data ./data.json --output ./sample.md --unquoteVariables 
8:56:58 AM - info: Creating file: ./sample.md
8:56:58 AM - info: Name: Fred
Payment due by 17 December 2020

Payment due on: 17 December 2020
bash-3.2$ 
```

Here is a fixed up archive: 
[empty-contract.zip](https://github.com/accordproject/cicero/files/5429553/empty-contract.zip)

**Comment by martinhalford** [comment]
Thanks @jeromesimeon - My bad on the missing import.  Thanks for pointing this out and sorry for wasting your time. Appreciate the updated doco too.

Regarding the mandatory nature of the `else` clause... I have to keep reminding myself that Ergo is a functional language and evaluates everything. I'm used to more procedural languages which allow the `else` to be optional.  All good.
