### ISSUE TITLE
Cicero Template Version

### ISSUE THREAD

**Issue by fnaeemgsi** [accordproject/cicero#600]
Hello Team,

I am using cicero latest version (0.21.9). Is there any way to allow cicero node package to accept multiple template version?

Please help me about that request.

Thanks

**Comment by jeromesimeon** [comment]
> Hello Team,
> 
> I am using cicero latest version (0.21.9). Is there any way to allow cicero node package to accept multiple template version?
> 
> Please help me about that request.
> 
> Thanks

@fnaeemgsi Apologies for answering this with so much delays. Could be a bit more specific (maybe with an example of what you are trying to do?).

You should be able to run various template versions as long as they are _compatible_ with your current version of Cicero.
