### ISSUE TITLE
[Question] Can I use Cicero in Ehtereum?

### ISSUE THREAD

**Issue by Gonza116** [accordproject/cicero#602]
(Probably this isn't the place to ask but I can't find anywhere else to do so, so if this issue should be closed I would like for you to tell me where can I ask this before actually closing it).

I'm doing a final degree thesis on smart contracts and I wanted to use Cicero, as it is agnostic, in both Fabric and Ethereum. However, I can't find any info on using Cicero in the EVM. Do you have any idea on how to do it, or in some resources I could use? Thanks in advance.

**Comment by dselman** [comment]
Short answer is "no".

Longer answer is that you could run Cicero off-chain and then write code to send obligations to Ethereum (this is what my employer clause.io does, for example). 

Even longer term there is a project underway to compile Ergo logic to WASM code, which should (one day) be runnable on-chain in the EVM via the eWASM Ethereum project.

**Comment by Gonza116** [comment]
Okay, thank you very much for your answer, it was super clear!
