### ISSUE TITLE
Pre Commit and Pre Push hooks for cicero repository

### ISSUE THREAD

**Issue by Cronus1007** [accordproject/cicero#624]
# Feature Request 🛍️
My feature is related to adding the pre commit hooks and pre push hooks as used in the web-components repository so that linting and testing errors won't arise during the CI/CD testing. This will make to execute the code right before commiting 
## Use Case
This will reduce the dependency upon CI/CD for the os used by the contributor as well the contributors will be able to know the linting mistakes before commiting.
## Possible Solution
Use of husky and lint-staged to manage the pre-commit hooks used in the repository.

Pinging @mttrbrts @irmerk @jeromesimeon @algomaster99

**Comment by irmerk** [comment]
Is there a reason to do it pre-commit and pre-push rather than in the PR testing checks?

**Comment by Cronus1007** [comment]
Git hooks used in this way are a sign of a team that cares about code quality and code maintainability.When developers start delaying commits, increasing the size of commits, or batching commits to defer pushing their changes, we are losing ground. Continuous Integration is about minimising the time any change is isolated from any other change. The pre-commit experience needs to be fast and frictionless to encourage the behaviours needed to achieve Continuous Integration.

**Comment by Cronus1007** [comment]
@irmerk @mttrbrts @jeromesimeon @algomaster99 Any updates regarding this issue?

**Comment by jeromesimeon** [comment]
> Git hooks used in this way are a sign of a team that cares about `code quality` and `code maintainability`.When developers start delaying commits, increasing the size of commits, or batching commits to defer pushing their changes, we are losing ground. Continuous Integration is about minimising the time any change is isolated from any other change. The `pre-commit` experience needs to be fast and frictionless to encourage the behaviours needed to achieve `Continuous Integration`.

I'm not entirely clear I am believing this argument. I think CI gives us the `code quality` and `code maintainability` we need on the code being merged into the main repo.

And I am not sure I understand how pre-commit and pre-push hooks would stop any developer from increasing the size of their commits or deferring pushing their changes.

I'm also not grasping what you mean by "minimising the time any change is isolated from any other change". Maybe you can elaborate on that?

Do you have specific examples that could explain what would be improved by this?

**Comment by Cronus1007** [comment]
I think this `Atlassian` blog may help to know much advantages about the `pre-commit-hooks`.
https://www.atlassian.com/git/tutorials/git-hooks#:~:text=Pre%2DCommit,-The%20pre%2Dcommit&text=You%20can%20use%20this%20hook,status%20aborts%20the%20entire%20commit.

**Comment by jeromesimeon** [comment]
> I think this `Atlassian` blog may help to know much advantages about the `pre-commit-hooks`.
> https://www.atlassian.com/git/tutorials/git-hooks#:~:text=Pre%2DCommit,-The%20pre%2Dcommit&text=You%20can%20use%20this%20hook,status%20aborts%20the%20entire%20commit.

ouch. I'm afraid I'm a little too busy at the moment to read through all this. Is there a tl;dr you could offer?

> 
> Moreover I beleive that in AP we should make the code structure of majority of the repos symmetrical. Thats why thought of bringing this up here.

Can you explain what you mean by "symmetrical" ?

**Comment by jeromesimeon** [comment]
Maybe more to the point: what specific hooks to you believe we should add, and to do what?

**Comment by Cronus1007** [comment]
> ouch. I'm afraid I'm a little too busy at the moment to read through all this. Is there a tl;dr you could offer?

Sure we can discuss this once you are free.


> > Moreover I beleive that in AP we should make the code structure of majority of the repos symmetrical. Thats why thought of bringing this up here.
> 
> Can you explain what you mean by "symmetrical" ?

Here I think that the repositories should follow same coding practices at least like hooks,linters.Since `web-components`  repository offers it so thought of bringing it up.

> Maybe more to the point: what specific hooks to you believe we should add, and to do what?

Pre-Commit Hooks and Pre-push hooks.

**Comment by jeromesimeon** [comment]
> > ouch. I'm afraid I'm a little too busy at the moment to read through all this. Is there a tl;dr you could offer?
> 
> Sure we can discuss this once you are free.
> 
> > > Moreover I beleive that in AP we should make the code structure of majority of the repos symmetrical. Thats why thought of bringing this up here.
> > 
> > 
> > Can you explain what you mean by "symmetrical" ?
> 
> Here I think that the repositories should follow same coding practices at least like hooks,linters.Since `web-components` repository offers it so thought of bringing it up.
> 

Ah yes that I 100% agree with.

I believe we have linting in all the repos, although there are some significant differences in linting for the React-based repos and linting for all the others. Any suggestion for more alignment on those would be welcome.

I am not aware of any react hooks (maybe we have some in web components? do you have a link?)

> > Maybe more to the point: what specific hooks to you believe we should add, and to do what?
> 
> Pre-Commit Hooks and Pre-push hooks.

To do...what?

**Comment by jeromesimeon** [comment]
> # Feature Request 🛍️
> My feature is related to adding the pre commit hooks and pre push hooks as used in the web-components repository so that linting and testing errors won't arise during the CI/CD testing. This will make to execute the code right before commiting
> 
> ## Use Case
> This will reduce the dependency upon CI/CD for the os used by the contributor as well the contributors will be able to know the linting mistakes before commiting.
> 
> ## Possible Solution
> Use of husky and lint-staged to manage the pre-commit hooks used in the repository.
> 
> Pinging @mttrbrts @irmerk @jeromesimeon @algomaster99

**Comment by Cronus1007** [comment]
Have a look upon https://github.com/accordproject/web-components/blob/master/packages/ui-contract-editor/package.json#L55 from line 55-60. I am referring this functionality.Here I am referring these as hooks not React Hooks to manage the linting and testing.

**Comment by jeromesimeon** [comment]
> Have a look upon https://github.com/accordproject/web-components/blob/master/packages/ui-contract-editor/package.json#L55 from line 55-60. I am referring this functionality.Here I am referring these as hooks not React Hooks to manage the linting and testing.

Interesting. I don't remember seeing those or those being discussed.

@irmerk Do you remember this?

@dselman it was in your commit here https://github.com/accordproject/web-components/commit/80b5f1ffbf6ddaa57875ce457a0952725ec57810

Could you explain why we're doing this in `web-components`?

**Comment by dselman** [comment]
I suspect is was because this repo was created using create-react-app template, or similar.

**Comment by jeromesimeon** [comment]
> Have a look upon https://github.com/accordproject/web-components/blob/master/packages/ui-contract-editor/package.json#L55 from line 55-60. I am referring this functionality.Here I am referring these as hooks not React Hooks to manage the linting and testing.

As a general matter, the maintainers have an enormous amount of work and I lean towards anything that will make their life easier and help them stay focused on delivering the features the community needs while keeping the overload small.

For that reason we try and keep a really high bar for "infrastructure" changes (like CI, linting, PR templates, etc) since they require a lot of work, unless they really add a very clear benefit.

I'm unclear that this specific issue / proposed change here passes that bar.

In that vein I believe those that are on our list would be much more valuable:
- better linting across the board
- the on-going switch to GitHub actions
- cypress testing

Concretely, anyone opening a PR should have run the test and linter locally before opening that PR.

**Comment by Cronus1007** [comment]
> Concretely, anyone opening a PR should have run the test and linter locally before opening that PR.

Yes here comes the role of pre commit hooks as before anyone commit they automate the above mentioned functionality.I think it would be better to close this issue since it has a low priority.Thanks for clearing my doubts regarding pre-commit and pre-push hooks.

**Comment by jeromesimeon** [comment]
> > Concretely, anyone opening a PR should have run the test and linter locally before opening that PR.
> 
> Yes here comes the role of pre commit hooks as before anyone commit they automate the above mentioned functionality.I think it would be better to close this issue since it has a low priority.Thanks for clearing my doubts regarding pre-commit and pre-push hooks.

Thanks for the feedback and suggestion 👍
