### ISSUE TITLE
OPEN SOURCE PROJECT

### ISSUE THREAD

**Issue by jwalapc** [accordproject/cicero#633]
Hey Myself Jwala ,I want to start contributing in open source project but i dont have much idea about it ,so anyone over here can help me in this thing .What should i do?

**Comment by jeromesimeon** [comment]
> Hey Myself Jwala ,I want to start contributing in open source project but i dont have much idea about it ,so anyone over here can help me in this thing .What should i do?

This isn't an issue pertaining to this repository. Please read the contributions guidelines before opening issues. Thank you.
