### ISSUE TITLE
Having problems using the Cicero Node.js API

### ISSUE THREAD

**Issue by rmarques20** [accordproject/cicero#663]
So I'm trying to use your Cicero Node.js API and I always end up having an error while trying to follow this [guide](https://docs.accordproject.org/docs/tutorial-nodejs.html). 

When I try to get the template I get an error about this code line regarding the await command

`const template = await Template.fromDirectory('./test/data/latedeliveryandpenalty');`

Is there anything I can do to make this work?

**Comment by dselman** [comment]
I suspect it is because `await` can only be called from an `async` function. 

This repl workspace may be useful:
https://replit.com/@DanSelman/Cicero#index.js

**Comment by rmarques20** [comment]
Thank you so much for your help, the problem is solved
