### ISSUE TITLE
Allow options to pass to JSZip when using fromArchive

### ISSUE THREAD

**Issue by rsilva-uw** [accordproject/cicero#665]
I have an API that provides me with .cta files encoded in base64, and from archive expects a .zip file. Although if I could pass custom options to the JSZip inside the fromArchive method, I could just say that I'm using a base64 file (https://stuk.github.io/jszip/documentation/api_jszip/load_async.html) and it would work just fine.

**Comment by dselman** [comment]
You can use `Buffer.from` to convert your base64 string to a Node `Buffer` object, which can then be passed into `fromArchive`.

Example:
```
// Base64 encoded string
const base64 = 'QmFzZTY0IEVuY29kaW5nIGluIE5vZGUuanM=';

// create a buffer
const buff = Buffer.from(base64, 'base64');
```

**Comment by rsilva-uw** [comment]
Oh, my bad. Didn't know I could do that. I was trying to use the `js-base64` lib to decode but then the template engine just throwed me errors asking for a zip file. Thanks for you help guys :smile:
