### ISSUE TITLE
CTA validation

### ISSUE THREAD

**Issue by lambdafu** [accordproject/cicero#673]
Just some random thoughts: We are thinking about validation of CTA files, at least at the syntax level. Are all required files contained in the cta file, does normalize run through with sample data, is the ergo code syntactically valid? Are these things that you have already considered? Of course, validating the logic of the ergo code is a whole different matter. Another idea: Unit tests inside the ergo code.

**Comment by jeromesimeon** [comment]
hi @lambdafu the Cicero library does a fair amount of validation already, from memory:

- validate metadata (proper JSON, contains name, version etc)
- validates the data model (`./model` directory)
- validate grammar (by building the parser, notably checks that the template variables are defined in the model)
- validate the Ergo logic (parsing and type checking)

You should be able to see that in action using `cicero parse` with various kinds of errors (missing package.json, invalid model or type error in ergo -- all of which should return errors)

Was there any validation that you felt wasn't handled already that should be added?
