### ISSUE TITLE
Outdated Contributing.md Doc

### ISSUE THREAD

**Issue by K-Kumar-01** [accordproject/cicero#738]
# Discussion 🗣

Currently, the contribution guide contains the link to Accord project slack channel. However, Accord project now uses discord instead of slack. So, proper statement update along with link should be done.

## Would you like to work on this issue?
Yes

**Comment by Ayman161803** [comment]
FYI README.md has a similar issue.

**Comment by Ayman161803** [comment]
FYI README.md has a similar issue @K-Kumar-01.
