### ISSUE TITLE
Failed Curl Request in Cicero-server package

### ISSUE THREAD

**Issue by K-Kumar-01** [accordproject/cicero#742]
# Bug Report 🐛

Currently, the request for [`draft`](https://github.com/accordproject/cicero/tree/master/packages/cicero-server#draft-request) and [`trigger`](https://github.com/accordproject/cicero/tree/master/packages/cicero-server#trigger-request) mentioned in the documentation for `cicero-server` is failing.

## Screenshots
![Screenshot from 2022-05-24 06-12-49](https://user-images.githubusercontent.com/59891164/169926487-01ea5319-dbf3-4753-95fa-b5d2af837033.png)
![Screenshot from 2022-05-24 06-17-45](https://user-images.githubusercontent.com/59891164/169928729-69a6aadc-9f7f-4398-b339-c72d1653421a.png)

## Expected Behavior

The requests should pass without any error and result in a successful execution with status code 200.

## Current Behavior

The error displayed in the above image is shown. Cross-checking with cicero-cli on same data gave the same error.
The data passed in the documentation seems to be incorrect.

## Possible Solution

Update the documentation to use proper data.
Sample data for proper `draft` request.
```json
{
  "$class": "org.accordproject.latedeliveryandpenalty.LateDeliveryAndPenaltyContract",
  "buyer": "resource:org.accordproject.party.Party#Steve",
  "seller": "resource:org.accordproject.party.Party#Dan",
  "forceMajeure": true,
  "penaltyDuration": {
    "$class": "org.accordproject.time.Duration",
    "amount": 2,
    "unit": "days"
  },
  "penaltyPercentage": 10.5,
  "capPercentage": 55,
  "termination": {
    "$class": "org.accordproject.time.Duration",
    "amount": 15,
    "unit": "days"
  },
  "fractionalPart": "days",
  "contractId": "c538755a-6c9e-43ff-8767-f8915d0336a0",
  "$identifier": "c538755a-6c9e-43ff-8767-f8915d0336a0"
}

```

## Steps to Reproduce

1. Use Postman/Insomnia or a direct curl request for [draft](https://github.com/accordproject/cicero/tree/master/packages/cicero-server#draft-request)
2. Repeat the procedure for [trigger](https://github.com/accordproject/cicero/tree/master/packages/cicero-server#trigger-request)

### Desktop
 - OS: [e.g. macOS] Zorin OS

## Detailed Description

Data Passed:
```json
{
    "$class": "org.accordproject.latedeliveryandpenalty.LateDeliveryAndPenaltyContract",
    "contractId": "ecd6257e-2ffe-4ef1-8a5c-38ca9084a829",
    "buyer": {
        "$class": "org.accordproject.cicero.contract.AccordParty",
        "partyId": "Dan"
    },
    "seller": {
        "$class": "org.accordproject.cicero.contract.AccordParty",
        "partyId": "Steve"
    },
    "forceMajeure": true,
    "penaltyDuration": {
        "$class": "org.accordproject.time.Duration",
        "amount": 9,
        "unit": "days"
    },
    "penaltyPercentage": 1000.5,
    "capPercentage": 88,
    "termination": {
        "$class": "org.accordproject.time.Duration",
        "amount": 5,
        "unit": "weeks"
    },
    "fractionalPart": "days"
}
```

Proposed Data:
```json
{
  "$class": "org.accordproject.latedeliveryandpenalty.LateDeliveryAndPenaltyContract",
  "buyer": "resource:org.accordproject.party.Party#Steve",
  "seller": "resource:org.accordproject.party.Party#Dan",
  "forceMajeure": true,
  "penaltyDuration": {
    "$class": "org.accordproject.time.Duration",
    "amount": 2,
    "unit": "days"
  },
  "penaltyPercentage": 10.5,
  "capPercentage": 55,
  "termination": {
    "$class": "org.accordproject.time.Duration",
    "amount": 15,
    "unit": "days"
  },
  "fractionalPart": "days",
  "contractId": "c538755a-6c9e-43ff-8767-f8915d0336a0",
  "$identifier": "c538755a-6c9e-43ff-8767-f8915d0336a0"
}
```

Here, on seeing we find that `buyer` and `seller` both are passed as objects in the former request and strings in the latter one.
This is what is creating this issue.

## Possible Implementation

Updating the documenation should work.

## Would you like to work on the issue?
Yes

**Comment by dselman** [comment]
Thanks for the bug report - looks great. Would you like to submit a PR to fix the docs?
