### ISSUE TITLE
Updates to common.cto to include Contract and Clause base models.

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/cicero#78]
- [x] Add Contract Model
- [x] Add Clause Model
- [x] Change Clause concept to be an Asset rather than a Concept so that we can use relationships
- [x] Change 'actions' to 'emit' which should be an array of CTO events

**Comment by jeromesimeon** [comment]
Handled by 9a65ee27a0219423ab46493966fe56b016ad9746 and 4c2a58cdeae35c22f9a08a9ee20ea4a2d78af88a

This still needs to be tested in context of the runtime (See #87)

**Comment by jeromesimeon** [comment]
This is now used when doing validation for contract state and emits. @mttrbrts One remaining question open is whether State should be an asset or a transaction? Do we really need a `stateId`?

**Comment by mttrbrts** [comment]
Conceptually, state is something that could be stored on chain. So following the composer convention, 'asset' seems the most appropriate to me. In either case this means that taking the hash of a state will be different on each request because the timestamp will be different.

**Comment by dselman** [comment]
Having state be an asset makes sense I think. Assets don’t have time stamps.

**Comment by jeromesimeon** [comment]
Whose responsibility is it to change that state id? The logic we have in some of the tests and sample make an attempt at that. Do we need the logic to return a new stateId when there is a state change?

**Comment by jeromesimeon** [comment]
I think #120 finally takes care of this. Can we close?

**Comment by dselman** [comment]
Yes, let's close this.
