### ISSUE TITLE
Add a tutorial that shows how to embed Cicero inside Hyperleger Fabric

### ISSUE THREAD

**Issue by dselman** [accordproject/cicero#8]
Use the v1.1 support for calling Node.js modules:
https://www.hyperledger.org/blog/2017/11/02/hyperledger-fabric-v1-1-0-preview-is-now-available

**Comment by jeromesimeon** [comment]
https://github.com/clauseHQ/fabric-samples/tree/master/chaincode/cicero
@mttrbrts are you happy to close this now? ;)
