### ISSUE TITLE
Distinguish between contract and clause templates

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/cicero#84]
- [x] Annotation in package.json to distinguish contract vs clause template
- [x] Add unit tests

**Comment by mttrbrts** [comment]
Cicero should have a top-level property in the package.json file for a template. We can then extend this with other metadata as necessary. For example
```json
{
    "name": "copyright-license",
    "version": "0.0.1",
    "engines": {
        "cicero": "^0.3.0-0"
    }
} 
``` 
becomes..

```
{
    "name": "copyright-license",
    "version": "0.0.1",
    "cicero": {
      "template": "contract",
      "version": "^0.3.0-0"
    }
}
```
`template` could also have the value `"clause"` to identify packages that contain reuseable clauses.
`version` identifies the semver of cicero that this template is designed to run against.

By default, the supported version is assumed to be the current version of the cicero environment and `template` is assumed to be a contract.

**Comment by jeromesimeon** [comment]
@mttrbrts added some tests. I think this is resolved?
