### ISSUE TITLE
Create a sample contract template as a spec for Contract Support

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/cicero#85]
- [x] Contract template grammar
- [x] Contract model
- [x] Contract logic
- [x] package.json config
- [ ] Contract -> Clause references, import
- [ ] Child clause templates

**Comment by mttrbrts** [comment]
Sample for Milestone 1
https://github.com/accordproject/cicero-template-library/commit/0270517c4b64ac079b318c56edf3b20bc831d5ac
