### ISSUE TITLE
How is the current time defined for execution of a clause.

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/cicero#92]
Most of the Cicero template use the timestamp for the transaction. Is that the right way to access the current time? Would the time at which the logic is called be preferable?

**Comment by dselman** [comment]
In general, I think it is better to use the time in the incoming transaction. It makes unit testing *much* easier as you don't have to use mock clocks etc.

**Comment by jeromesimeon** [comment]
As of Cicero 0.12, API calls for parsing and execution lets the user pass a "currentTime" parameter in the following format: `'YYYY-MM-DDTHH:mm:ssZ'`. This parameter is also used to determine the local timezone for execution.
