### ISSUE TITLE
ContractState model has mandatory ContractModel relationship

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/cicero#97]
In `cicero-common/models/common.cto`, 

The ContractState relationship to the ContractModel should not be optional. This will allow us to run queries to find all the states for a contract of type X, or the state for the contract with ID 123.

- [ ] Update all unit tests
- [ ] Update cicero-template-library

**Comment by dselman** [comment]
The relationship has been removed - so we can close this now.
